---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: gatus
spec:
  networkRouterRef:
    name: home-router
    namespace: networking
  serviceRef:
    name: gatus
  groups:
    - name: Admin Resources
