apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
stringData:
    api-token: ENC[AES256_GCM,data:Kcuh9jGGhENP1k/PAmAHDOWq3jLLjLhq/5LRxdJAkna2lSPPn9zBPr2VPzJYHyUJ/FFjePW0FEY=,iv:AcJ111p1Yt9YhMJmSPrAfNLNcZ2TvoBVXQA+iGC5y5o=,tag:0ujR3Xi+T69ms6r92nCu4Q==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcVJhUDF6YzhNeTNIMXZv
            ZEw4U3pVTlZ5M0JrUHlOZSthQUdnN0hNREVJCnNtRXZDemlhT1VNdHI2bkVkb0Ux
            MzJFZnZiSHJTMXhHWXVpUURiSjQ5NDgKLS0tIENGMjltWDNqdzJPdHdaOWdZNDhN
            bWFhLzEwbUtLakozdkpvRlEyY2p1QzAKMKJQKpQUESUAAfeFEPs1Nze56z3zIMsw
            Cb5sIT1nYTahYp9altz7mRf5qQWIC+6ccsMhsd7EXvc51og8+LmIeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T11:12:49Z"
    mac: ENC[AES256_GCM,data:CuwTHk8SmjrazsA3U3groAR4fUygASJeHQVtbEu9zXqDMXYmbYM3Te0tCihwcgqRYa+3UfTKpbuWV/SRk1VIflYxhp1dSGds7JJNe5wQsC8oqd9Z38WWDHyOucZP8WhUGspNjz9RYAwLnH9EHWiBdKQIAZLSRqFLkqLm9WBcrbM=,iv:ZHflEZf676mEVyr4nAhnl+5T5gcsFdif7xjJqR12b2k=,tag:nQFuNJMXLxMHfWx18B3XFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
