---
- name: Update and Upgrade Packages
  hosts: proxmox
  become: yes

  tasks:
    - name: Wait for automatic apt operations to finish
      ansible.builtin.shell: >
        while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/lib/dpkg/lock >/dev/null 2>&1; do
          sleep 5;
        done
      changed_when: false
      tags: [maintenance, packages]

    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
      tags: [maintenance, packages]

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      tags: [maintenance, packages]

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Rebooting to apply kernel updates"
        reboot_timeout: 300
      when: reboot_required.stat.exists
      tags: [maintenance, packages]
