---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: grafana
spec:
  networkRouterRef:
    name: home-router
    namespace: networking
  serviceRef:
    name: grafana-service
  groups:
    - name: Admin Resources
