apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
stringData:
    client_secret: ENC[AES256_GCM,data:WGaya7wXAllr1oOQXAQYeX0AWbV72hlJRF2tBgcoMlk=,iv:AwsWlUKK9Ev4UVV4ME2j/OJYI/z5KEzD4Xo86EPxJf0=,tag:YFC/jQPQQw3zsBfdlkrkXg==,type:str]
    admin_user: ENC[AES256_GCM,data:poH+kJh4ZCgH4jsGlKqiwQjLW7Py8n0=,iv:sDXZqF5pXvRP8zYFVV3EK69McYIMlRuWP//KJrjL+kk=,tag:yi2ZHZTOX4HQjAb5+PZFeQ==,type:str]
    admin_password: ENC[AES256_GCM,data:9XGtdFdWh0+5LhKL2nKRRkHBTAsTVc4aERo=,iv:E5v2b+rSH+aOrEURb8oM1LTbLvYplQi9ZxcJCP1md6c=,tag:UFYyxSYkPHTEzhmlhmkasg==,type:str]
    admin_email: ENC[AES256_GCM,data:ab40A0zzH71ad4Dc+suAhUQNohqNbcs=,iv:uotID8gNsK/I9t5z1NKpE7NJftED0l/SP1kZW58fJjA=,tag:nZqurB1y6zOO74rha+xeuw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T10:56:41Z"
    mac: ENC[AES256_GCM,data:XpufYXUlJviRqvLXm4Lk7WxGGXAKtcXQndJ3McBQWGvWzgHPuIqh4Kaa7Q4At5lqFP14/cLlOdA9PWwo0sLpoRjWkLzkyi8s0ZGbGUkSOuDPSp9xu3N7ZAtLoYT5yY593pF8iutzM81Xm0iJlLx3jHv3cz1/aRqU5H+63DuIvK4=,iv:v3GY8xTfiC/bonexf4y7ou4U/2O9Vd/KU0V0OMwF6AQ=,tag:YwE+96UAOBroyaiCtBsPIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
