---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-app
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-base
    - name: longhorn-addons
    - name: cnpg
    - name: volsync
    - name: hashicorp-vault-app
    - name: external-secrets-app
  path: ./kubernetes/apps/apps/nextcloud/nextcloud/app
  prune: true
  wait: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nextcloud
      namespace: apps
    - apiVersion: apps/v1
      kind: Deployment
      name: nextcloud-imaginary
      namespace: apps
    - apiVersion: apps/v1
      kind: Deployment
      name: eurooffice
      namespace: apps
    - apiVersion: apps/v1
      kind: StatefulSet
      name: nextcloud-redis-master
      namespace: apps
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: nextcloud-pg
      namespace: apps
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: apps
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-backup
  namespace: flux-system
spec:
  dependsOn:
    - name: nextcloud-app
  path: ./kubernetes/apps/apps/nextcloud/nextcloud/backup
  prune: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  interval: 15m
  retryInterval: 15m
  timeout: 15m
  targetNamespace: apps
