---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fin-sqlite-data
  labels:
    app: fin
    component: api
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: fin-restore
  resources:
    requests:
      storage: 1Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: fin-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-fin
    storageClassName: longhorn-storage
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    capacity: 1Gi
    enableFileDeletion: false
    cleanupCachePVC: false
    cleanupTempPVC: false
