apiVersion: v1
kind: Secret
metadata:
    name: restic-fin
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Ry6JPUBbdR3aAlBXffhEor7FWBgXTCcQE+8O1DRRuLJ8Lmmj9oAAAgPbWW1W,iv:N0R/cqDAUZeA/FN9YyoS8V8GlyyVPFd/I8zKeosqMb4=,tag:ny8RNANabZYKJzk+kU/7Zw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DSAoJgQGwPdT98gi29JoElbaZgccUOpQFx2VOCv5Lgij0Vp4P021Da4YV8Ouz4NYYZDbrt8=,iv:+tutQu/qwd62qkspfOEY5cHmhwdzgAyzt15d/Z49BYk=,tag:uNg0xm0hszCVrXrDUfOSCw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T20:40:41Z"
    mac: ENC[AES256_GCM,data:TLpeEKnGM8YkTXSx5ZvmeymHcHoT2pZxrOID/bTHD9Z1lLkQ6BFDXT1U/RbJ26/MsskIVWoAID8KyeBZ2Kczdp2Lk55Cx3Ylz1C4Cejoy1GXLC7wyjAKalhTTEsK7mr1mMSc4+2em66TPOtf9WKtF6EWHKZT3t/cz40yU7JzvLQ=,iv:pygFyBw77SHTs31JBtSRLa7aRrBYKBfuNZf+rLATW3g=,tag:XyPEN7XVNIHajkGuyetV5g==,type:str]
    version: 3.13.1
