---
apiVersion: v1
kind: Service
metadata:
  name: fin-api
  labels:
    app: fin
    component: api
spec:
  type: ClusterIP
  selector:
    app: fin
    component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fin-web
  labels:
    app: fin
    component: web
spec:
  type: ClusterIP
  selector:
    app: fin
    component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
