---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-livesync
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: obsidian-livesync-admin
  dataFrom:
    - extract:
        key: apps/obsidian-livesync
