---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-mcp-data
  labels:
    app: obsidian-mcp
  annotations:
    numberOfReplicas: '1'
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 1Gi
