apiVersion: v1
kind: Secret
metadata:
    name: obsidian-livesync-admin
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:3Vg2t5I=,iv:j/CJzzh4BhFjRHOSAjCQZBCbKTnL9OokFuxm5ge8a8E=,tag:uzxz33fJhn+u5ksoGdL9HA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:zDTv+jLZemCCy/mGSPcIvVpZD8EhEsqyEVgCiT8QqI+MEfR2lgFgg8+t,iv:u0m3hu0u0lTyGXv8XlIiWM2XGOLPXQxUi7EYrrz7LGc=,tag:eLJ2kAb02bzV5uNk99VzqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArblFpWWNzeC9JaGN0ZGFk
            SmhGTlpjd0R4QTdvbGluVllVOXFhRUF6SFFVCk51enV4M3BtaERiOGxuR1VhaXJL
            OGdMVXBTcjNkUmNsTk9vbFBMaUZMWGsKLS0tIG5yczc2MGZRUDJiZm1aQ2ZORmxX
            SzJ3NnFRbHBFc1NQUTI5Q2FRQk9SN0kKqXkHM+0zLDstqo9GxQwk/c3UauluG5Yy
            Q9ZSAAgRw9OEzPvnEXS3HAGDRu71ofM0asF5k50vjYAxLEVRdL4/tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T12:59:22Z"
    mac: ENC[AES256_GCM,data:QRNWkyknpSDBpZ6Hqu25/UCcbYKZYKc462D/7Sb0/x8b+i8mNfnlb1C3tDAWeJnSuLigokNgM5MXqLuQGV4aUM4XHrYeD6aGV/Mfyu24AS48UMdcIqchQlrOab72UfuQjUvhcUTUqRpaW+Ng0Rn2fuLKmttAOBkEFQ0XvkKn2zc=,iv:8ApSbST+2WY3V+uhNUNYR/HW7QcKANkjDubuKQh8J4o=,tag:S03vP+4if8/v3aO9vFq0mA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-obsidian-livesync
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:lbPUAyiIvHL1IVjtSBaf32fzPUXQ1ucNMemC9ZPHy2/h1nsdARDOcBP/cpi26Cd7Z3DU8IOzYw6vzpw=,iv:nBPeT6W9GzhmTr4pIjo2RbKODM814+kJmr4ZkG1reUo=,tag:w9ls/SzovsEEYMMbLLtjRw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:jzzNeaWeu20LxJ5/waklDkPZ2MjgyBJAnMYsUd48rv4sxqb14iyHD1jK1R/pERu8zI6W8w==,iv:HThFOeHjUtggdDD2vUy9MrgVLGADO+xnxheczWW6RdQ=,tag:wk6C/6PLdoiThEJ/BD7AgQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nmBX07aoGIAlY5LCBeA5wKyQALE=,iv:mPuaUO5XkBIti6VV8rW7OT1x8cEmJxU+EIwWlU4giCA=,tag:6/MQgzI4XuMNk6E/qDU4WQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IUiT1TVFedZcW0/I3jkQ+a15YnEwjgJW7HvE3tI1gc2JwSkwFyCFjw==,iv:fnusnLO+jNSaojpy//KtkxeQG0ymevOZmcLi7d8CwqE=,tag:i6ryLqGvV5QmcuAUj+fYbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArblFpWWNzeC9JaGN0ZGFk
            SmhGTlpjd0R4QTdvbGluVllVOXFhRUF6SFFVCk51enV4M3BtaERiOGxuR1VhaXJL
            OGdMVXBTcjNkUmNsTk9vbFBMaUZMWGsKLS0tIG5yczc2MGZRUDJiZm1aQ2ZORmxX
            SzJ3NnFRbHBFc1NQUTI5Q2FRQk9SN0kKqXkHM+0zLDstqo9GxQwk/c3UauluG5Yy
            Q9ZSAAgRw9OEzPvnEXS3HAGDRu71ofM0asF5k50vjYAxLEVRdL4/tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T12:59:22Z"
    mac: ENC[AES256_GCM,data:QRNWkyknpSDBpZ6Hqu25/UCcbYKZYKc462D/7Sb0/x8b+i8mNfnlb1C3tDAWeJnSuLigokNgM5MXqLuQGV4aUM4XHrYeD6aGV/Mfyu24AS48UMdcIqchQlrOab72UfuQjUvhcUTUqRpaW+Ng0Rn2fuLKmttAOBkEFQ0XvkKn2zc=,iv:8ApSbST+2WY3V+uhNUNYR/HW7QcKANkjDubuKQh8J4o=,tag:S03vP+4if8/v3aO9vFq0mA==,type:str]
    version: 3.13.3
