apiVersion: v1
kind: Secret
metadata:
    name: restic-actual-budget
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:AxZpH+RoetWud/KYs7X0+oYEV7TsPwKRe1PBarnipvMc8Q/K+SCO9YE5y2yT+2GGexETSmH67A==,iv:lNJY9jdmvo6Xus7g6UjKssTe0NKDIF48QYkrHb6CGfk=,tag:j2FCH6f6A0gba3FEEUEKlQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Fprb+LshXkzzO61qC1DzZUBnsBllCo+MoMwYLVKvETPwOuHs6iPTcJlkx2mGgvZanQ==,iv:PhExiEiumj8K77ecF1lFz+Ubhvn9ebMt4tYuw1dTKi8=,tag:Ji+/vqmJmS2NzuTZqADcKA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T18:54:18Z"
    mac: ENC[AES256_GCM,data:WbJBgAjyp2ZC0mlzj7bYQCyYckPA/hnh4KVvz2Gps2UM2znqmiYko6BvOwQbyv8GL+h1H+lO+HzMew3m2tjMPT2iR9tKIaaIVI0obyZDeIJ2uBEXRZeBH6kIBcw5Dr69QYOxdTDW/n4fYr1Qrwe0dGOa8jmQ73JPveBMocqfPG0=,iv:8Mu0sIhMkfAdxm6DnZwcEcE4z/YfS7t0VYB6Wr7xk8I=,tag:0vy/Q9zv7ICOJSvNnJ+Q7g==,type:str]
    version: 3.13.2
