---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - rules.yaml
  - volsync.yaml
  - cnpg.yaml
  - cert-manager.yaml
  - flux.yaml
  - longhorn.yaml
  - services.yaml