---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: paperless
spec:
  networkRouterRef:
    name: home-router
    namespace: networking
  serviceRef:
    name: paperless
  groups:
    - name: Apps Resources
