apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:b+rn4flLQ2yYsP/W6lr8bqtlMeiP6n96OW6WcXgWiqVLbVUjYMowhB2YtgxgRMOiWLMy4HdSq0pKWQoPRuuj1Q==,iv:gaNYDEfUm4DmZv9UjXLA7LxA8vRaC+D46OmvRClbBUs=,tag:lIiFa6rMRWx1+GMWODUpbA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:lb+uxjVzwvDDrw==,iv:BkR/m0srXx1NEAv/zMZ//1vMR7XG+GgJXVVgIBTcLgs=,tag:mV2xXkJMqRgRBwrg7a73YA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BQ23uwTOHPXhY1OE/ARIACTtDGnCt3vE7/kOYFMsrPZyNW/V+CuGLJ3lTKBXrjYpGEHw/UjNk59F5Pw3SSM29w==,iv:ZXE0DIZcY2oKkpTwAJGXx/zuj4p/Ln3gkj3kpup4r4U=,tag:kge4qH/sj0gS1X9YNhgDeQ==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:DZsc60BKSnjO+6yrXQ8Boj4=,iv:S7khTNE2NIcxeeQrUr+WgjTfVJYL/xURr6nN82QIpsw=,tag:CDAQnZshGnbpDl+FqwCtPA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:gDbgHTgdGBKCazA254Tb6QOCaUxf2EbpAJ208aUqwHevbO7TOKprnATu0pRZpBy+8vUoxtuz+rqjWN1Q8a0hnAQ1hd4RlXvwpnklBE6cqbVrpXaEX4wbOkS6WstPK9SwI0hs3EM2iXByX1IJBsP6PKQJXhDaiLVMjsMp0ZUYM3yG4MFpffypD1flrI2I2dyfpEgVMYZJq31PqVHZKzUQxLg3bilKjfJUM3IrEv2sj2n8Uwxj66Rx4DXEgDWU+m/x0cfjh4qjlWwnHSokLcrhQCV+IM4IJticXuHFWJB6fFy0krjz2KW4oLzT1ztu79ETqTk2fLA4Vfmn284xtt/HVS6iugcDhMwTI5eWbivcV9UecUZyqSCn5ih0FFq5sYLF+eJ6dpKqOA==,iv:my6EWbHScuHjqm8oyM0itCwM+4Rkq8CIPxxK/b7uzN4=,tag:FbhebwmSHFtPsnPOGkeV0Q==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T12:53:44Z"
    mac: ENC[AES256_GCM,data:K02PeT7Gd1MjWdfz0BFxrMUu9uAo7T5Qr+ZAKWNnsbe/c6F787vYhRnC9y/Ncagrji3TTf4vb+Nlz5cPuTSrqj2YMi8mfmGe/78E14jDEdIsRp/Ij8PrlQsfYr8LqS46RuMyOxqlkcxnbE4rTv07hniodSVP6nv20aXYWa45MXg=,iv:MuHg0gTGiHzmEjfy/5b+xlL3a6tQmz4X/f160RTzQfc=,tag:uWF0fI2RJm62JR1bCoweeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-paperless
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jEuXR0WthUnTnDXCeQGJcufCg7X/AAGWCTdjjs+hwv8VNWoFNbKrCutifAIn2Zj7b7R7,iv:4mVugfwhAHKXyXY7HrgDTakoHlv/2r4rvnQ1PkxAFzw=,tag:JsX/MR+hUEF72Fs6Y8o0KA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:h5PpwG0Hqe8z/FbteSA1EhMzg8KGKlGDHExczcxM4n9ifJFspQwF2+s2,iv:QRFMz0aIl1l1iU5IGyHLQhXK/eNgwqc9JKc1+q+dF+8=,tag:vvDIsQe6wqRNWg3fh6+wvA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T12:53:44Z"
    mac: ENC[AES256_GCM,data:K02PeT7Gd1MjWdfz0BFxrMUu9uAo7T5Qr+ZAKWNnsbe/c6F787vYhRnC9y/Ncagrji3TTf4vb+Nlz5cPuTSrqj2YMi8mfmGe/78E14jDEdIsRp/Ij8PrlQsfYr8LqS46RuMyOxqlkcxnbE4rTv07hniodSVP6nv20aXYWa45MXg=,iv:MuHg0gTGiHzmEjfy/5b+xlL3a6tQmz4X/f160RTzQfc=,tag:uWF0fI2RJm62JR1bCoweeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-paperless-pg-backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hXJjWTttitZg1wy02bcJhcx9AMA=,iv:yit2T99IlrscB8qES+74GUTWcadFEmpm0WOL9RoHRrY=,tag:k/0ukdsQTZj9kQxnzFTTEw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LUW3e3rDcfHTuHXPURMXfzNL7gk14nKCJjAU08o0m7WmHOMRJc2wfA==,iv:IgkZSlR4eJmr87DFE+TQVDOO2c60JLqnHkOHMb1hbb4=,tag:JJFsaO+vpQFA3aOdt5f1nQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T12:53:44Z"
    mac: ENC[AES256_GCM,data:K02PeT7Gd1MjWdfz0BFxrMUu9uAo7T5Qr+ZAKWNnsbe/c6F787vYhRnC9y/Ncagrji3TTf4vb+Nlz5cPuTSrqj2YMi8mfmGe/78E14jDEdIsRp/Ij8PrlQsfYr8LqS46RuMyOxqlkcxnbE4rTv07hniodSVP6nv20aXYWa45MXg=,iv:MuHg0gTGiHzmEjfy/5b+xlL3a6tQmz4X/f160RTzQfc=,tag:uWF0fI2RJm62JR1bCoweeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
