apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:b+rn4flLQ2yYsP/W6lr8bqtlMeiP6n96OW6WcXgWiqVLbVUjYMowhB2YtgxgRMOiWLMy4HdSq0pKWQoPRuuj1Q==,iv:gaNYDEfUm4DmZv9UjXLA7LxA8vRaC+D46OmvRClbBUs=,tag:lIiFa6rMRWx1+GMWODUpbA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:lb+uxjVzwvDDrw==,iv:BkR/m0srXx1NEAv/zMZ//1vMR7XG+GgJXVVgIBTcLgs=,tag:mV2xXkJMqRgRBwrg7a73YA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BQ23uwTOHPXhY1OE/ARIACTtDGnCt3vE7/kOYFMsrPZyNW/V+CuGLJ3lTKBXrjYpGEHw/UjNk59F5Pw3SSM29w==,iv:ZXE0DIZcY2oKkpTwAJGXx/zuj4p/Ln3gkj3kpup4r4U=,tag:kge4qH/sj0gS1X9YNhgDeQ==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:DZsc60BKSnjO+6yrXQ8Boj4=,iv:S7khTNE2NIcxeeQrUr+WgjTfVJYL/xURr6nN82QIpsw=,tag:CDAQnZshGnbpDl+FqwCtPA==,type:str]
    PAPERLESS_AI_LLM_API_KEY: ENC[AES256_GCM,data:yWf6Qz756A==,iv:mTHJ+CbDOkFhuTgFD9LyWIBDzxbcCZnJcu8svStxlhE=,tag:GA/ovHUGSXIQHj92rs6KRQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:WEBIoP2mIL3BU/Us4Hri8kU5CWToM0IyTeSz7eLR1/zf1B3p15WA/6vRsiioAmbKwnujb/yjbVQBv6L/NOOA0xcjU3agLi3mFkjtpgpeVz5ktLkIG/6R3vt2zrdnQN53EcJ1FMBYkkweb9naVTyVF/72LO5ZqtTzO0Z3YnAUKitv9V8w0+NOUT8OtCxyVomFmPYampvrSG1+mriM4BQ4rEnJELtrq6BCmkmD5sRpxMj7OqpNPXN8ClqJBzyerFW9YswQlTp9g5bNBxpYK1aarCVXscQPA0r961atSdPFKJ8/oLmdrYv3me301an5Ic16/se6uBCvQ1K1lV7aI9KH/3Qxhd1hICoPV2Xy+yZfo5pryF1dynOmH1/NLcNUtGP3rEB3mJO/ROWOxLRnBg==,iv:9W7jo6YTn6ay0ncuFCI12tKzfEsYxjxywrHgb//5iIE=,tag:lLMPctPI6S05Ab0cuWdT2Q==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T12:22:14Z"
    mac: ENC[AES256_GCM,data:mRLTN8LtPkSccIHGJE6PfU6AHpHgpACTVKUlhFNdGH9ZdWJV6L1WybC9Tpg0GFxy0TSW9KCCPV6vR0QAh87OCkAaK2LtfPk2N+KrLgMwXH0UuBl88aC1FZtxpXi56aXQG1SbHdVbpcvEc1rBz6VTUoZPRBWP++A741pRTcaR0do=,iv:TW/aFS/CK1ioxnZfdpqMgK95w5uJf63lB5vpIj+0zP0=,tag:lvenhHd2S3dyFHY+KiSbQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-paperless
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jEuXR0WthUnTnDXCeQGJcufCg7X/AAGWCTdjjs+hwv8VNWoFNbKrCutifAIn2Zj7b7R7,iv:4mVugfwhAHKXyXY7HrgDTakoHlv/2r4rvnQ1PkxAFzw=,tag:JsX/MR+hUEF72Fs6Y8o0KA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:h5PpwG0Hqe8z/FbteSA1EhMzg8KGKlGDHExczcxM4n9ifJFspQwF2+s2,iv:QRFMz0aIl1l1iU5IGyHLQhXK/eNgwqc9JKc1+q+dF+8=,tag:vvDIsQe6wqRNWg3fh6+wvA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T12:22:14Z"
    mac: ENC[AES256_GCM,data:mRLTN8LtPkSccIHGJE6PfU6AHpHgpACTVKUlhFNdGH9ZdWJV6L1WybC9Tpg0GFxy0TSW9KCCPV6vR0QAh87OCkAaK2LtfPk2N+KrLgMwXH0UuBl88aC1FZtxpXi56aXQG1SbHdVbpcvEc1rBz6VTUoZPRBWP++A741pRTcaR0do=,iv:TW/aFS/CK1ioxnZfdpqMgK95w5uJf63lB5vpIj+0zP0=,tag:lvenhHd2S3dyFHY+KiSbQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-paperless-pg-backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hXJjWTttitZg1wy02bcJhcx9AMA=,iv:yit2T99IlrscB8qES+74GUTWcadFEmpm0WOL9RoHRrY=,tag:k/0ukdsQTZj9kQxnzFTTEw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LUW3e3rDcfHTuHXPURMXfzNL7gk14nKCJjAU08o0m7WmHOMRJc2wfA==,iv:IgkZSlR4eJmr87DFE+TQVDOO2c60JLqnHkOHMb1hbb4=,tag:JJFsaO+vpQFA3aOdt5f1nQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T12:22:14Z"
    mac: ENC[AES256_GCM,data:mRLTN8LtPkSccIHGJE6PfU6AHpHgpACTVKUlhFNdGH9ZdWJV6L1WybC9Tpg0GFxy0TSW9KCCPV6vR0QAh87OCkAaK2LtfPk2N+KrLgMwXH0UuBl88aC1FZtxpXi56aXQG1SbHdVbpcvEc1rBz6VTUoZPRBWP++A741pRTcaR0do=,iv:TW/aFS/CK1ioxnZfdpqMgK95w5uJf63lB5vpIj+0zP0=,tag:lvenhHd2S3dyFHY+KiSbQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
