apiVersion: v1
kind: Secret
metadata:
    name: restic-paperless
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jEuXR0WthUnTnDXCeQGJcufCg7X/AAGWCTdjjs+hwv8VNWoFNbKrCutifAIn2Zj7b7R7,iv:4mVugfwhAHKXyXY7HrgDTakoHlv/2r4rvnQ1PkxAFzw=,tag:JsX/MR+hUEF72Fs6Y8o0KA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:h5PpwG0Hqe8z/FbteSA1EhMzg8KGKlGDHExczcxM4n9ifJFspQwF2+s2,iv:QRFMz0aIl1l1iU5IGyHLQhXK/eNgwqc9JKc1+q+dF+8=,tag:vvDIsQe6wqRNWg3fh6+wvA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T06:01:24Z"
    mac: ENC[AES256_GCM,data:7DJO/yFWCm0UhUBCEnoTMNR6tmJ66YJdPHvXv8jWhGuhS96NUvAxU7ejAWq20HQh/tMmxAzcrhvtj5FJchOrlQrXodtFwgp33O4gJPAkim5H9a1qSPUMILjJQ3Qii0wmV5IqkfGDo2xFP1T22ztIlFIPNoWmiL/J+RllIC4uz+Y=,iv:BmFVLMdVG0nwQJAt+z6R33hT/DcL1/amxyZLEOrK4ys=,tag:QUcs7ymwsIwvW6bW2UThyw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-paperless-pg-backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hXJjWTttitZg1wy02bcJhcx9AMA=,iv:yit2T99IlrscB8qES+74GUTWcadFEmpm0WOL9RoHRrY=,tag:k/0ukdsQTZj9kQxnzFTTEw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LUW3e3rDcfHTuHXPURMXfzNL7gk14nKCJjAU08o0m7WmHOMRJc2wfA==,iv:IgkZSlR4eJmr87DFE+TQVDOO2c60JLqnHkOHMb1hbb4=,tag:JJFsaO+vpQFA3aOdt5f1nQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T06:01:24Z"
    mac: ENC[AES256_GCM,data:7DJO/yFWCm0UhUBCEnoTMNR6tmJ66YJdPHvXv8jWhGuhS96NUvAxU7ejAWq20HQh/tMmxAzcrhvtj5FJchOrlQrXodtFwgp33O4gJPAkim5H9a1qSPUMILjJQ3Qii0wmV5IqkfGDo2xFP1T22ztIlFIPNoWmiL/J+RllIC4uz+Y=,iv:BmFVLMdVG0nwQJAt+z6R33hT/DcL1/amxyZLEOrK4ys=,tag:QUcs7ymwsIwvW6bW2UThyw==,type:str]
    version: 3.13.3
