---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.0/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: kube-vip-metrics
  labels:
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/component: metrics
spec:
  # Headless service - kube-vip runs on hostNetwork so we target the node IPs directly
  clusterIP: None
  selector:
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/component: daemonset
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
      protocol: TCP
