---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-vip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
