---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: netbird-operator
    namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    managementURL: https://nb.traunseenet.com
    netbirdAPI:
      keyFromSecret:
        name: "netbird-mgmt-api-key"
        key: "NB_API_KEY"
