apiVersion: v1
kind: Secret
metadata:
    name: netbird-mgmt-api-key
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:ZjP9jUXUsmIVsc6atNPhl+fN2ToaYpl4LjQREFaCmk30O1NimRDREw==,iv:rKR7FpV2RWXf1acZeYO4mPQcJYuMVdfF0ugC4gLGhR8=,tag:dw+toT7sIdElhXwrwFhlAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T16:09:20Z"
    mac: ENC[AES256_GCM,data:sqtYRSVQdclhx1jWMdTTX2E/5k9dspOKG9kJsL7w0pFHOkO4rIn7NzYr3pqNBHX89xydKDBaTC2dUzbSHS3w/oi5XuWz4wDOW9mH+wqwveIiiGjWdraIPPf6R13R59kyZmZ8OBl5TgEP9MEum8U9u0PyA58R3bKRD0sEOJ2gN/g=,iv:2EdOgf5qUhhg9gglIOaSjEvLRGaaKH9HcI9+c9AZTAI=,tag:Na3KsBTY+vLSeectLQONDA==,type:str]
    version: 3.13.1
