apiVersion: v1
kind: Secret
metadata:
    name: netbird-mgmt-api-key
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:zNhQovijnvTEdeeg6YWKLs9hejuhgKhy0wdtNFoeb6p9tT2LsfEL/Q==,iv:LMZn5tQyoY7hK0UxlGuPxKiMVjuK1EPDXSy8wo2sEp8=,tag:TtiXHQCQawUq9NlSy7Cl9g==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T09:47:42Z"
    mac: ENC[AES256_GCM,data:r3VGFK/VGT0sF0odGO2HqQDgnm+z3thQAkH6DvxuL4s7Jq826wWDtXDeGcmC+JMYpdB+pUu+CEadkf7aEoOYhBFVse4pzwtSfDik14W56oSOQHTSAnWenuZNlpvzdpjl8DdBVydBM+FA2y+mGgTrjbnUdQoLJvUSX37NRzsiBes=,iv:HKlSuQgWlx3XDpdEb4YB981/pa8vpWs7NIlhmAokjtg=,tag:YdqOuEnhiFxtLj8txUfUnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
