---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocketid
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pocketid-secret
  dataFrom:
    - extract:
        key: auth/pocketid
