apiVersion: v1
kind: Secret
metadata:
    name: restic-pocketid
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:h6tv3BN9mTPp1/B3R0Bew4KXNz298euDVaIQmKE12+ys+U1xdhiKx1nN40OrRoM38io=,iv:WjwJTWwLR/tSedAFHhqhiSpDoSRjpyn4Fiwd2FVDee0=,tag:Kiw6hAJ2kiIvqSD8dD744A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qo7u6PqwArXfj9p+6yt44Cv58TDWOa48WvFYd073OhxgPeboKor/PA==,iv:jBpv8/s6aNNEIf2tQwiK32IxabdYMAJP3kMxGEBItGg=,tag:16BGHlgkDx6gtw4jPomVBQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TFRPEGEndtVmrJvoEpLoTO2nEvc=,iv:KIJFoAkhzXeaKeTNtttMmc+YBnLN7EgjADyGAEBUIxc=,tag:YwjPMDIY6VGrdtCe9ouWDA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2x3pKPzwkBLCc+Ve0xckDArZyqdoRI3iw8lXJlyp39n1HS3lHXwq8w==,iv:Zkd8NCt5cNl3KVs59zDVh/zJIqBFtOhBQf1OpTqBdis=,tag:FC0qMAkjAuDUCe98WJXaOg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T10:50:31Z"
    mac: ENC[AES256_GCM,data:g1b3z9amN3FBidTm4Zk+TSmMWPYhFI0VdCEn3QgTwGdT+8lw0LnOMumiQNkOj3Jguo/9BC2Q2gvVyHcQkR2EzIyjieFrBiiIgZdsFfvHPXd0vS+XmbKuDouvl4OOYwmftAiRwlSbuYYPqywuoznECmDF0cIKU+bSphz3f1guRvA=,iv:W/oVI2AW3fq++RQvS9sFBaLaPsd5yrzLC8D/bb1CbCo=,tag:GgKBsmvWomvDnYgWzEA5YA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
