---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openshell
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/nvidia/openshell/helm-chart
  ref:
    tag: 0.1.2
    digest: sha256:7a714bbbbcef7b5ed8dac599e89e89df12eb623fa4454d22f89df41d6f047e2a
