---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tns-csi
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bfenski/tns-csi-driver
  ref:
    tag: 0.19.2
    digest: sha256:2f78aa38c016f81467665fc474ade62f1dbc9370dc07e501b2d813e0e16afdae
