---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tns-csi
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bfenski/tns-csi-driver
  ref:
    tag: 0.19.1
    digest: sha256:2cde9cda76f809457419565a8093809512ee1b1cbfcedabe6f23e1483a881b1d
