---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bifrost
  dataFrom:
    - extract:
        key: apps/bifrost
