apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bifrost
  name: bifrost-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: bifrost-restore
  resources:
    requests:
      storage: 5Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: bifrost-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-bifrost
    storageClassName: longhorn-storage
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    capacity: 5Gi
    enableFileDeletion: false
    cleanupCachePVC: false
    cleanupTempPVC: false
