apiVersion: v1
kind: Secret
metadata:
    name: bifrost
stringData:
    BIFROST_ENCRYPTION_KEY: ENC[AES256_GCM,data:RhOzlgQGb8EunwLHKvdyieDM67Woj+zQZokKk2O+WYPPLXi4qwmiAk14951YMi/x0suvkeSxHa7yjW2Lo+DfJg==,iv:Tu6YDTip0RbLP4EukbBCBE3LlPOu+h8Iw5yW73vXmGE=,tag:5PWdno/XG1qZNI633kjXsA==,type:str]
    GITHUB_AUTH_HEADER: ENC[AES256_GCM,data:C5DIHDGKF9mq0jHxLstZO5dE2hV666UJc2as0tMriHPkVa9yEeJOiG7tu3mOB9oNpUITCh90zbXTkl9MEF3Iw3kNwN07p+dHKQ94LJi67aKhB5Zi3wLzZXlZEJIVZFcTx47EQw==,iv:pa40+fDTIJeSBoOrkcRdfVZ1KDsYDu4smFIwmyO6IaQ=,tag:ZCdDCTkXQAoePYMQdS4tqg==,type:str]
    MEMOS_AUTH_HEADER: ENC[AES256_GCM,data:mg7GRs6EKKdtXXMIVjObUIPFq//x3IfUtiJGuniyw4dL+imhOlrF1IjCxRDR8AR+ag==,iv:g3AsIYo9A6nhzTxjaO8EWjl4guYNpasyfvzRzXJeQ0g=,tag:+69vpRBZgYYKlu/LdZUF9w==,type:str]
    TREK_AUTH_HEADER: ENC[AES256_GCM,data:QwWx0pzK2xvdumt8E4f7ckUVVxdVOh1umpZRXrwAGL/Sgv8CzLfy9sDgJ3+nGtnv3YJ1w7ObMV6O2QLe,iv:arcPQ3KJug7wROUmzZkMqko49mJ2ge3b7qP66uIEH+o=,tag:WS5XGIzboU+mwbjJR3cpIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T06:37:29Z"
    mac: ENC[AES256_GCM,data:8YLiBAwLe7xMp7/z47ly1ktl4qJPqRXcAJXNxi+dLpuktZa1Ip3SZXgAeT0knlKiZnvPQ5CSTyeEiXmvEZxq1tboWjlqvMrZ/6ccAP40a4vOpPcim1my86heiuX6Nkm5mMbUAXxXaC7mOplrx066qRa8zrgniQx8ddf86hMrOjo=,iv:OYH38DmcszXpCx2Eko9mnyUDNmfnkJjX1cm3+w2vP1M=,tag:13JP/j559r7QT0xE2rbakQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-bifrost
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4lH1nPhGMiE4Aob5k9leI7Fsufu5+mE06ZgzKPB8XB5ogJeMug29yKiger2aAciWrw==,iv:vSA4w/hfhObiW1S9glvmoqSezAvjBNRUjAbZMLleots=,tag:lEGB2ulFzh2CRpPbNcPvXg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qMcm+E327lRgRa1dEiLTqGBZRnB5s6rAexKjJYCfSm9xYctFjRcc8Gq5,iv:JLkjRQ4c5ub4hTL/n4RI0ImZR6NdRBENQPUNnzyKXVo=,tag:BgOlBh6zE/5a6+X5rYGKDQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9fwD6Y00rNddzMUoSKHYBXeCQnI=,iv:WU6Wth0vf8F/TN9IhNcG9CUEO6SjtVD+ljucbOMdblQ=,tag:UuAc9jonV/ZTHjrkJIyqxQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vymDvqEaoPxEDg8fgjSnq5oqc0QvACRL5EabvHRI10+TdlmVxUXE2Q==,iv:uz75+ANVa3SCHbysCG6L/InvdJ+qs6jn2aW9YAnZy2U=,tag:w+53jRDLmcTUHnauzdKSCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T06:37:29Z"
    mac: ENC[AES256_GCM,data:8YLiBAwLe7xMp7/z47ly1ktl4qJPqRXcAJXNxi+dLpuktZa1Ip3SZXgAeT0knlKiZnvPQ5CSTyeEiXmvEZxq1tboWjlqvMrZ/6ccAP40a4vOpPcim1my86heiuX6Nkm5mMbUAXxXaC7mOplrx066qRa8zrgniQx8ddf86hMrOjo=,iv:OYH38DmcszXpCx2Eko9mnyUDNmfnkJjX1cm3+w2vP1M=,tag:13JP/j559r7QT0xE2rbakQ==,type:str]
    version: 3.13.3
