apiVersion: v1
kind: Secret
metadata:
    name: bifrost
stringData:
    BIFROST_ENCRYPTION_KEY: ENC[AES256_GCM,data:RhOzlgQGb8EunwLHKvdyieDM67Woj+zQZokKk2O+WYPPLXi4qwmiAk14951YMi/x0suvkeSxHa7yjW2Lo+DfJg==,iv:Tu6YDTip0RbLP4EukbBCBE3LlPOu+h8Iw5yW73vXmGE=,tag:5PWdno/XG1qZNI633kjXsA==,type:str]
    GITHUB_AUTH_HEADER: ENC[AES256_GCM,data:C5DIHDGKF9mq0jHxLstZO5dE2hV666UJc2as0tMriHPkVa9yEeJOiG7tu3mOB9oNpUITCh90zbXTkl9MEF3Iw3kNwN07p+dHKQ94LJi67aKhB5Zi3wLzZXlZEJIVZFcTx47EQw==,iv:pa40+fDTIJeSBoOrkcRdfVZ1KDsYDu4smFIwmyO6IaQ=,tag:ZCdDCTkXQAoePYMQdS4tqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T18:17:25Z"
    mac: ENC[AES256_GCM,data:VY9StEuIqsjez28J47uVAL4CTKUEM/BelVzB+buSdPC+plKdOI7PSSiHz0MEfWxEI5xCTRkyAcXa0VrGaEvjru3cCqkSXsPqtlfNJf6B4vRojS7xcgNQCVfTMmMwSUN/wzMxfBi0maYZwbIJhR+x8WieO/uw67meK5OpvHi3zVA=,iv:FaorYec0XjA2BuauMPoHGdwQbCQhMPv368H3n/Uffgs=,tag:0MrujoR7BiAwQspIUs2A6A==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-bifrost
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4lH1nPhGMiE4Aob5k9leI7Fsufu5+mE06ZgzKPB8XB5ogJeMug29yKiger2aAciWrw==,iv:vSA4w/hfhObiW1S9glvmoqSezAvjBNRUjAbZMLleots=,tag:lEGB2ulFzh2CRpPbNcPvXg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qMcm+E327lRgRa1dEiLTqGBZRnB5s6rAexKjJYCfSm9xYctFjRcc8Gq5,iv:JLkjRQ4c5ub4hTL/n4RI0ImZR6NdRBENQPUNnzyKXVo=,tag:BgOlBh6zE/5a6+X5rYGKDQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9fwD6Y00rNddzMUoSKHYBXeCQnI=,iv:WU6Wth0vf8F/TN9IhNcG9CUEO6SjtVD+ljucbOMdblQ=,tag:UuAc9jonV/ZTHjrkJIyqxQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vymDvqEaoPxEDg8fgjSnq5oqc0QvACRL5EabvHRI10+TdlmVxUXE2Q==,iv:uz75+ANVa3SCHbysCG6L/InvdJ+qs6jn2aW9YAnZy2U=,tag:w+53jRDLmcTUHnauzdKSCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T18:17:25Z"
    mac: ENC[AES256_GCM,data:VY9StEuIqsjez28J47uVAL4CTKUEM/BelVzB+buSdPC+plKdOI7PSSiHz0MEfWxEI5xCTRkyAcXa0VrGaEvjru3cCqkSXsPqtlfNJf6B4vRojS7xcgNQCVfTMmMwSUN/wzMxfBi0maYZwbIJhR+x8WieO/uw67meK5OpvHi3zVA=,iv:FaorYec0XjA2BuauMPoHGdwQbCQhMPv368H3n/Uffgs=,tag:0MrujoR7BiAwQspIUs2A6A==,type:str]
    version: 3.13.1
