apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bifrost
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: bifrost
