---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-base
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/traefik/traefik/base
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: networking
  interval: 15m
  retryInterval: 15m
  timeout: 5m
  targetNamespace: networking
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: traefik-addons
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: traefik-base
#   path: ./kubernetes/apps/networking/traefik/traefik/addons
#   prune: true
#   # wait: true
#   sourceRef:
#     kind: GitRepository
#     name: fluxcd-kubernetes
#     namespace: flux-system
#   interval: 15m
#   retryInterval: 15m
#   timeout: 5m
#   targetNamespace: networking
