# Classic PAT scopes for the default toolsets: repo, read:org, read:user
# (fine-grained PAT scoped to specific repos is recommended)
apiVersion: v1
kind: Secret
metadata:
    name: github-mcp
stringData:
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:MT3oEGmydax0bNo+RzcTM2wigEJH/9NALfFSMQBnfmOGnHNQDXmJ+46Af5cJ9eOw144NFfHaYyHEmKX3WS4qVjVDbwOdZMfa9OCoI2HTO+JH99LyqGNklBIS5aRB,iv:+Y5uElvfduf00dj7TFOaal+Wlv+9qOH+2jj9Y/ZBZtM=,tag:83OMYWA+FM5UAx055IMpQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T07:07:19Z"
    mac: ENC[AES256_GCM,data:Th7w0C61Xt1fKBUA8V2neCICNsmAGCh51P36WAOjJBcAld2i06/BrkmxbFG/OLRheqe3M7CGImDJm7DAwFHonoCAw+cSHfYzxCVLhcKkle5ip/AR9lwtbAyPVGUrexFdn8VDaTw8iArmpB8Q3xADGYDWhHJHzh7VT+/Dgi8mbP8=,iv:uDaM8kiub/zJHK99pUFXOEliHwdqOVfTPyy2PEh20Rc=,tag:N7wbfx7bUP59IUiajot1gw==,type:str]
    version: 3.13.1
