# Classic PAT scopes for the default toolsets: repo, read:org, read:user
# (fine-grained PAT scoped to specific repos is recommended)
apiVersion: v1
kind: Secret
metadata:
    name: github-mcp
stringData:
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:rLhyk8lizVTOI7N3Gw4DqGYrzQ==,iv:N6Abt7SX578m68Nj7R+lWxPMaF0N/XEH4d/57U4PWkg=,tag:1CNYf7m1p00i5kZBLMdNYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T19:35:14Z"
    mac: ENC[AES256_GCM,data:jR0DseRAiSaXrLE5q8khgbQEPL66ry2Sgv+R8SBcm2fMmv3zlznhJtYDika/PPJnyuFhkacoWgp9F+v/evBObOBNwB0ZYfnrmFusakKvOTnj3+rX4gtFyEH0f8WxYzvazrwrbVJrkS9rq66ibqnhm2GNC7l0ErQsnktaYI9G4Lo=,iv:8vx1gjZihL5zMo5jef+InXJMuEcdZG4+JMS+4GRqq1E=,tag:IHkmM5t26/tGSBtmyvEarg==,type:str]
    version: 3.13.1
