# The real values only exist after `vault operator init`; see BOOTSTRAP.md.
apiVersion: v1
kind: Secret
metadata:
    name: vault-token
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ULsjHUWWifM9RegVldQXgiNEih5hfq/+KGx2y9Ggo6juvHQ8AmY5SsuKIX26FlA4coU05eRnF9OStPe4qr+akvsF69cQ8htN27pSvw==,iv:Un+rCuf1H10bLkuVtnM90Q9AECMR1SdDU+3fMoycu4A=,tag:fjaelXB2sE7VbGJkvmxCPQ==,type:comment]
    VAULT_AUTO_UNSEAL_KEY_0: ENC[AES256_GCM,data:UNLThHhhlsXyE0fYhtnO9jXk2w==,iv:e57/liQNjl1iwPwUTdmdP8W+P35geiqEKB4S+3gjgbw=,tag:zWOZN/YlBeBYTV5yLYyTPA==,type:str]
    #ENC[AES256_GCM,data:o3h1JR9NI4Kq4feL4EHWHddFlgR+Fr0yLHHVhR0MMXAc6+Ozgfo30aIW1gc8M/EmQK0T6XB5e/v9MJzcqDwXKFlG8XbO4qncJTg=,iv:18agI+kISDDBedDjpgJWeNOs52BnRYakxtJ2oSjpI2g=,tag:Q7uAMlcmG3HeSvVb71QRgw==,type:comment]
    #ENC[AES256_GCM,data:+QON9blIfGjYDjMohi/gbHoia1ZtH4REHy2KoTV+fQHxyi6UiQEJiznohs28ttioSSw4GwW9/PKJHeMSniHiyWX8uyLVng==,iv:KCQVQY0a/zRttx1BWgDkPxcpUYv8Af4tTKqTRgTiPH4=,tag:cB/FoZy3YttB1POVHQD8xw==,type:comment]
    token: ENC[AES256_GCM,data:SI/ys5amtE227bQsQ+HD,iv:LjACjvUg8X77NalJNjmRoE51FTGuNSXgWDUZHERt2cA=,tag:AnYrcN8e0kfc2v0vltNGMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T13:27:55Z"
    mac: ENC[AES256_GCM,data:fDBRSZi19yH79Z8zzcJZV45wJEeDC23GPHT3O12Yc77EgBtMu7/8blDBVofXs2OTXgbv5yUSqS8rb4j4Qpf+ZgLI7PpO3BLwP0M611+HgDSbe83q8FRPVevNkPEIm3pDYP8YH/Mw3OJBskazGPeYX7MWgBDLT6H2NFZpyS1XvSQ=,iv:vqLLU+7eSwsgEnXq7NzhyM+syn4YArj3CNG6Yqbpw5M=,tag:5zwj2+U0Rkigbhccv3aMIg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-hashicorp-vault
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:s3PAG0bZjj6e347H/c+Kgl3Au59d0Nqa6uy6AXj/Obdyqn0eD3ADurrd8uY40fvh3aE2VTxgo+up,iv:BQy7rgj0KPcYu51eyzREegxkqa0HfzvjRcZ5mHzeppk=,tag:aScHVR88yzNDXMuyVm1Grw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Ag8wjIMWxDIXDjGuCBdMfRWP1GQe5p1WjIsscEj9Qk8u,iv:L3sCUiK+Ad4u0RcPlbHibl3XGf2+etMxbeJ3XVfg/WI=,tag:XJo5bqXFlKU54++fT+3Hqg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TFRPEGEndtVmrJvoEpLoTO2nEvc=,iv:KIJFoAkhzXeaKeTNtttMmc+YBnLN7EgjADyGAEBUIxc=,tag:YwjPMDIY6VGrdtCe9ouWDA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2x3pKPzwkBLCc+Ve0xckDArZyqdoRI3iw8lXJlyp39n1HS3lHXwq8w==,iv:Zkd8NCt5cNl3KVs59zDVh/zJIqBFtOhBQf1OpTqBdis=,tag:FC0qMAkjAuDUCe98WJXaOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T13:27:55Z"
    mac: ENC[AES256_GCM,data:fDBRSZi19yH79Z8zzcJZV45wJEeDC23GPHT3O12Yc77EgBtMu7/8blDBVofXs2OTXgbv5yUSqS8rb4j4Qpf+ZgLI7PpO3BLwP0M611+HgDSbe83q8FRPVevNkPEIm3pDYP8YH/Mw3OJBskazGPeYX7MWgBDLT6H2NFZpyS1XvSQ=,iv:vqLLU+7eSwsgEnXq7NzhyM+syn4YArj3CNG6Yqbpw5M=,tag:5zwj2+U0Rkigbhccv3aMIg==,type:str]
    version: 3.13.3
