---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: harbor-portal
spec:
  networkRouterRef:
    name: home-router
    namespace: networking
  serviceRef:
    name: harbor-portal
  groups:
    - name: Admin Resources
---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: harbor-core
spec:
  networkRouterRef:
    name: home-router
    namespace: networking
  serviceRef:
    name: harbor-core
  groups:
    - name: Admin Resources
