---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: harbor
  name: harbor-data
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: tns-csi-nvmeof
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: harbor-restore  # Name of the ReplicationDestination
  resources:
    requests:
      storage: 1Gi
status: {}
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: harbor-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-harbor
    storageClassName: tns-csi-nvmeof
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    capacity: 1Gi
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true