apiVersion: v1
kind: Secret
metadata:
    name: restic-harbor
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:2+fUXHu1qoi6m64VE27kCwv7BhK599YnIGoVzreKGScZDIi63+0RjPH3tWaoDSq9A2bH/ALsPo7M,iv:ohgoEcYqUm66Z5UoChd6kjtx3IBoLLud/Joz/WK6j8w=,tag:LckJB+vk4dEs6o1JIyw8fw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:9FxdyErcV3/qYxGEhSPNegpYwkxw89kuVyg03Yzaqy04iOxKFQ==,iv:Z4EY3nGVR3oaZCMJRnhQM0Bk4QhBgfFVGdTQM1XhZvI=,tag:Q1rOI/iJYiw/5AvQ6fHgRQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Gl+nuY06FweSLPIF4z+JOsEaQdI=,iv:NiJ4wqaL3Y/dn1g8/28vVAdwfEmdkUtgeo7uPnBKQXE=,tag:+sUM1jkwdzgqTVaNcBnXnw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2ach8HlBd9XZQTWODwRp7kl67BpPYFJWqvHEC7OWbaKaTo+eq2Fp4Q==,iv:u8xUtwP+1R1T1BjTmEwyaDqL1sM4zjtlYSmNGo8ojrg=,tag:YHlGBJt2wE1KFK4fJgx+2w==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T11:46:07Z"
    mac: ENC[AES256_GCM,data:e72djk/pgiyp7Ce0cAMH+92xLA2IAgi+XGGu93aiUTUIBm828Ssd7nLTN92SCttbS7jqGHFzn+xROnqzU+O51OB3cK5XA4oigebkG2CC1Lvvg162mhwCYrKcbadU5LlQL4XwoENDvYQ1aip6FSqQW7pppH4YYsZNX9dLYroTVZc=,iv:YiAsSpZmIsF/c/6ZFuTeXDfO8ppU0CIU9siESmSQf4U=,tag:/KVf1tsyG1Suci6rRAYp5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-secret
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:+lHJuCQZf/LYk1Fw/blaZko/a3rONVg=,iv:NpKK0+zrgfgY5uag20a/mP/2tc6oqRaXHQ8x5TDA0hs=,tag:HZ8ZeEbkfKZu69egDegSaQ==,type:str]
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:CxM8vNLlf9D1VE1nfV0/M9Y5SaE=,iv:0hOvKRZQiuV9kYh5p4np6PPd4GjL3LIk0IJpAHkhQ10=,tag:37dVwnnr7F7irRIPk6U13A==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:bGL+4bfb6smt9kghx8+QkPKcwumaErZDwKy12XKPkVFLYk550daYuw==,iv:F2UUbHUKPw/vN6FucB/A9k3cHwIXlFkmznZNearuHjA=,tag:jTxBzCWrn2KQkQQOi9Olyg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T11:46:07Z"
    mac: ENC[AES256_GCM,data:e72djk/pgiyp7Ce0cAMH+92xLA2IAgi+XGGu93aiUTUIBm828Ssd7nLTN92SCttbS7jqGHFzn+xROnqzU+O51OB3cK5XA4oigebkG2CC1Lvvg162mhwCYrKcbadU5LlQL4XwoENDvYQ1aip6FSqQW7pppH4YYsZNX9dLYroTVZc=,iv:YiAsSpZmIsF/c/6ZFuTeXDfO8ppU0CIU9siESmSQf4U=,tag:/KVf1tsyG1Suci6rRAYp5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
