apiVersion: v1
kind: Secret
metadata:
    name: restic-harbor
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jZzueFH2WJmNPMu50F+hQP7SgPq8jQLhWvsaln5P5nE8lrNxpniamrT8TFZAnxfv,iv:SngAF8RNz+1Lrx2lxKeQIwZun86wrHFqhFo2z1v5fVU=,tag:g95UWjr8+YkJjMImhpTEvg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:9FxdyErcV3/qYxGEhSPNegpYwkxw89kuVyg03Yzaqy04iOxKFQ==,iv:Z4EY3nGVR3oaZCMJRnhQM0Bk4QhBgfFVGdTQM1XhZvI=,tag:Q1rOI/iJYiw/5AvQ6fHgRQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Gl+nuY06FweSLPIF4z+JOsEaQdI=,iv:NiJ4wqaL3Y/dn1g8/28vVAdwfEmdkUtgeo7uPnBKQXE=,tag:+sUM1jkwdzgqTVaNcBnXnw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2ach8HlBd9XZQTWODwRp7kl67BpPYFJWqvHEC7OWbaKaTo+eq2Fp4Q==,iv:u8xUtwP+1R1T1BjTmEwyaDqL1sM4zjtlYSmNGo8ojrg=,tag:YHlGBJt2wE1KFK4fJgx+2w==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T13:59:27Z"
    mac: ENC[AES256_GCM,data:3VnhRRrMQBaa+43cA1PCP7RJCrmlViPhgojFZWYHQsk4gKwdPiQj/TxPiMWiUh3unZRrRgDYdPxVW1ELJ2o7KXX+hmXaQPONe5NCcikErVfwZxH5Swrw3DRS8ZYF8v99I+gL47WsABfuA6R48skFJy+z03EtObR8QfrCuvBCuWs=,iv:CNUYboaN5Gja52umoGgkIMNzsZ/vElIMSua71X8LtwQ=,tag:Ezq6yehW3kJdCp6+I6brPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-secret
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:+lHJuCQZf/LYk1Fw/blaZko/a3rONVg=,iv:NpKK0+zrgfgY5uag20a/mP/2tc6oqRaXHQ8x5TDA0hs=,tag:HZ8ZeEbkfKZu69egDegSaQ==,type:str]
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:vlzd9sI7LEIUMUR1eUQyOQKs9Ao=,iv:F248Ym0znJeVCTuEOfXAeDhQM+AhFnJtVZ40WqJNg6g=,tag:Z2IUzFX/4d1QEhDA51iMkw==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:aEt3FnLhcmEFk9qz51u76pimGeJmN3qWemSFL6MDoBpj5mJZoW9EGw==,iv:7Ze2huzoZar20msqhDgJ5lF0PBeamqc51x51ydkZ5i0=,tag:Ke9Z71YdRWItnY7ZXCUPPw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T13:59:27Z"
    mac: ENC[AES256_GCM,data:3VnhRRrMQBaa+43cA1PCP7RJCrmlViPhgojFZWYHQsk4gKwdPiQj/TxPiMWiUh3unZRrRgDYdPxVW1ELJ2o7KXX+hmXaQPONe5NCcikErVfwZxH5Swrw3DRS8ZYF8v99I+gL47WsABfuA6R48skFJy+z03EtObR8QfrCuvBCuWs=,iv:CNUYboaN5Gja52umoGgkIMNzsZ/vElIMSua71X8LtwQ=,tag:Ezq6yehW3kJdCp6+I6brPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
