apiVersion: v1
kind: Secret
metadata:
    name: restic-memos
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:mixmEiKEv2Dd9hQjZ6EUco2Nq+RqU6zx0tK1TY11/Y5RNwZFIAATvoQUOzj1n/btWz8=,iv:I2Ok5EVPcPtk9UcC8FLnWCHHPRTOI5wMMBtLVBTIkRU=,tag:I91Ayx+wocHM8/MQpWJwvg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:oq04TQ5gWH7m7FLaeEykcwUiujuF6fS9VgHoHfzCeXnVmiAFquC0R9b+CFDu6ns4my4=,iv:GCvuGfSi3vhKgDtKS7qP1tVio+bulfKY/HiMh0xOt7M=,tag:I0FhhFCvEJ4vlShIKgu4VA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T20:19:20Z"
    mac: ENC[AES256_GCM,data:gBJcVn7SfhvYGR7gm9sRcFfbT8Yv4ZOE83+/e679Jlz4NdhdVXbQ+m2rkn01garX2XBtFZBmBK1qMJeXpvzni3QQQowUvwCSJ4orfCGsgEuK8HxFl4A5d+JYDNUOFeKzUFhuzZuvXlcpQz9Ze6DOdXaac4trInu6IDTE0m5PPZg=,iv:pVeCTfc7wHHGBvPT/yicfAQRboKC1lgmdkcHOL+fd0g=,tag:wTWFYs1DDx+2ycaJtAODUQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: memos-idp
stringData:
    memos-idp-pocketid.json: ENC[AES256_GCM,data:ILG3Xe0/pc9qX7b4LcD5eRsptz53nIqdU9cgVb2IHHSVxqJgu9C1uD2eXE7EKe6fVkxzmPhMtd4CZ/wVUuTcVZrlOU+c/J/Rt15RcHLu1JWA8FDdSMfzcBJwhp4w4VQ5vR328ULBB0YKWXK9quS6E4tt5IA9O/hNXxAhJfoHpTqxKF7dtefQZoXMTfQb+okdYcpjI6DmszYs2XIE6GiKxlZj6RUG70qe/8aItCyis3DtcPhlQBUf9TfYQPrKXY8PH5yGY2DNkQ+ndonPCvRaKEks4dWFhbDBIlPG1NeJLxPTxXPHw46DkUW4o3sfxA3U1rgkpRRxQaWPJIpJITamaqV5IP0Job2P+akYvBYzWyPJZXhYVGHui57+duZKBOhUi01M+74UswaRUUdI3KzGGuR16bELeDC3rXrf5Ykrf/3cMNKTEmhUQl5GHIvqENKJ75H7c+9RgdsDXfFAnIBTyQNwim685OELkBAw9QmHB7gaur0mTUXx+YD9eo5KIz6Qvi8qy9JTG9DvhI2lbASLWZ2GbcdY9ZvPTKRJXGKz+57BPFt2xzJ2B2i0QwtObzONBBtXLeN/Li/wAiEZ6LxgkfCYlvGlwPPZgITsTyYKCKA67GcyxGa8L/6BeqODZjY+pUH9PBs59/JAKx3dMmmL3JXOHFNRh/3XGtbC6aYrGhUMnwIQ6UiCd2MRBY1SdeEzgCcJNqgRKREnehD/JuvE8YdvKsgfPcZW7O227uSXVSCQxZQXeUu0+NdqB2eyySh+9/JG0Lj7ZYb5eWXx3GACgg0QKR8WbgAC5vm/B9LXPBztTouK8PrF8jlqbc8Odmpcl/victaidEEaMJF4MiHvj50C5u2/mtONG1cUE02K5XIAtSIfCQ0uT4IZ,iv:8EJ+0USApx79q/fT7QkBzT7oR2zsgiomGY5pbUkuXQk=,tag:NSaVOBqNqRDLluvgfoX3gA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T20:19:20Z"
    mac: ENC[AES256_GCM,data:gBJcVn7SfhvYGR7gm9sRcFfbT8Yv4ZOE83+/e679Jlz4NdhdVXbQ+m2rkn01garX2XBtFZBmBK1qMJeXpvzni3QQQowUvwCSJ4orfCGsgEuK8HxFl4A5d+JYDNUOFeKzUFhuzZuvXlcpQz9Ze6DOdXaac4trInu6IDTE0m5PPZg=,iv:pVeCTfc7wHHGBvPT/yicfAQRboKC1lgmdkcHOL+fd0g=,tag:wTWFYs1DDx+2ycaJtAODUQ==,type:str]
    version: 3.13.2
