---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memos-instance-setting
data:
  memos-instance-setting-general.json: |
    {
      "key": "GENERAL",
      "generalSetting": {
        "disallowUserRegistration": false,
        "disallowPasswordAuth": true,
        "weekStartDayOffset": 1
      }
    }
