apiVersion: v1
kind: Secret
metadata:
    name: restic-gitea
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:IjsmogCUdv1DkIJ6EZpVHV+lqykbcV3FWvUDcSq5Zew97ls6TwoU9pqYfSgAaa4=,iv:/NOAsUHDvDARRx8Q4cJHLVmuS8B29OjvD+d79fB4Cyw=,tag:/9RWrB3Qfn11KmHbXlmYZg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:IXj30+0MzCnGirHDsxkTVNdBoKQ9M7zjDSKuRXcNdNKf/MaJUCGodqQ=,iv:DuyNLQWpVW33kKUIbXctWF6Q7alaWIlGK5aoT5S8Uqw=,tag:7pXgaRdqTSNnSTYh0NZgbw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T10:28:57Z"
    mac: ENC[AES256_GCM,data:dmOivkIwzKJm0kKrTL38dDWbtIHwAAMAlhsFtltpQWhkxpCy/dCIPZp4RvMvIMyU8Fj/lYVkbzDNaUsZBzGY75WJNGFy2wc94yV19tMKTTzJ8qYEQoaL0yzr+TDoGg20IYUe58BxOFjtaxFkJiOuT9JLyElm4rs4kwB1mz3Rk9w=,iv:Gj+zSpK1fsg5kBKX10QPoNoeOZ1HzE6CxQCvvqmts4w=,tag:IN85xclcMvaEsSAkYpma9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
