apiVersion: v1
data:
    kid: ENC[AES256_GCM,data:SO97C+uWTxVpB1NizbzRHOR7j8erdj3/,iv:L/+1oTKqBNSjQXS6cyBC7D9ZsVySf4WNX5qAeTmj7r8=,tag:vgjGj19UHco/N5rk8R1y0g==,type:str]
    public.pem: ENC[AES256_GCM,data:WwCsw/U8lSb6hUXtDpOYH0VUslcIVtwx/ONhms8UeWGwDntLNkU0sYQrvwJyfV29W/p/s/3AH8OTMK3n+xyIWMPdmNhUh/GrSLwHw/5w41iQ3Uv2iLwBfTUWp8RtiQSqVax9tiz47Ba8oZNb280H7uKqSGS6N7lirpz61JdOcNuia/jG8rbCLzsqf9tkYtaokb5RyGBcZ6g=,iv:RbXoVVQdgghxBJqoKS8lnwCoX9S97Yz5EijA30uza10=,tag:Z6EpNt/SU6C5CV2AJXAR3w==,type:str]
    signing.pem: ENC[AES256_GCM,data:CZp25/feRspCefLNqA4DgbHd1Xj4+FSg/85yuOEAVV785pgZeWY9cPa1QOpt+BZDkQKJ1+jDusuL834Do/oezcmQDbNsr8RpWAnxkL5j12JytQpg9Ub44hkzFlg9pcjjWSgrxiCQyJYRM8ia9NQg5EOlArfuP0TdAVF0GdreOnRBzJdXH31gvKAadAg60xqwFtRYo7i6PZE0ffOo7tqZ7A==,iv:RG0utKfm4PRjEO/08/wZBh+loY0cqC/L3s82c9oGn+w=,tag:hpOpOY7QftloxIb5KS8Y4A==,type:str]
kind: Secret
metadata:
    name: openshell-jwt-keys
    namespace: apps
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTEpydDU0SkppdzRpcGJn
            WlkrME93MzRmR0xlR0Nvd0E5RmxVdlM5WXdZCm9iMWxzd05RODJScDEyeW4ycWQx
            alNPTWVISURzRHRWcmVYUkdnYU1TaFkKLS0tIDNlYmFsZ0hMd3V4THlQU29XdkZZ
            aDdML0FoMzlWemc5VkVKTkJwaXBhQlEKMaxrdXPPDiRMS08DRurpMKSTehsP+JZJ
            VXQJgfCPIYUzIa8wYGKrEBTYliDHdxeBxsmifQqEssL+504XZoNCXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T18:44:54Z"
    mac: ENC[AES256_GCM,data:JY0zF91YVA0iPtQzZcs03IhxMuNjrV3rRaS3I+tO8xhu6VktSCmjC+WUiuOBAzLR/1CLhgddEtFlDTvDF0wiSz17tLuHn4ORnQDbVdCMTyXyfGo5TsvVpzFEqLtJoDqazwLWtRtU469cgxsMxPjdcoIMx1gzH7RqtjVNHwjlGjc=,iv:aWwGjt0QDmZYeLLsf9k8GIoJAiZSAKpZjSMrYSNv22s=,tag:oeB/ASEfIUY9n2WV+U2x3Q==,type:str]
    version: 3.13.1
