apiVersion: v1
kind: Secret
metadata:
    name: openshell-jwt-keys
    namespace: apps
data:
    kid: ENC[AES256_GCM,data:SO97C+uWTxVpB1NizbzRHOR7j8erdj3/,iv:L/+1oTKqBNSjQXS6cyBC7D9ZsVySf4WNX5qAeTmj7r8=,tag:vgjGj19UHco/N5rk8R1y0g==,type:str]
    public.pem: ENC[AES256_GCM,data:WwCsw/U8lSb6hUXtDpOYH0VUslcIVtwx/ONhms8UeWGwDntLNkU0sYQrvwJyfV29W/p/s/3AH8OTMK3n+xyIWMPdmNhUh/GrSLwHw/5w41iQ3Uv2iLwBfTUWp8RtiQSqVax9tiz47Ba8oZNb280H7uKqSGS6N7lirpz61JdOcNuia/jG8rbCLzsqf9tkYtaokb5RyGBcZ6g=,iv:RbXoVVQdgghxBJqoKS8lnwCoX9S97Yz5EijA30uza10=,tag:Z6EpNt/SU6C5CV2AJXAR3w==,type:str]
    signing.pem: ENC[AES256_GCM,data:CZp25/feRspCefLNqA4DgbHd1Xj4+FSg/85yuOEAVV785pgZeWY9cPa1QOpt+BZDkQKJ1+jDusuL834Do/oezcmQDbNsr8RpWAnxkL5j12JytQpg9Ub44hkzFlg9pcjjWSgrxiCQyJYRM8ia9NQg5EOlArfuP0TdAVF0GdreOnRBzJdXH31gvKAadAg60xqwFtRYo7i6PZE0ffOo7tqZ7A==,iv:RG0utKfm4PRjEO/08/wZBh+loY0cqC/L3s82c9oGn+w=,tag:hpOpOY7QftloxIb5KS8Y4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTEpydDU0SkppdzRpcGJn
            WlkrME93MzRmR0xlR0Nvd0E5RmxVdlM5WXdZCm9iMWxzd05RODJScDEyeW4ycWQx
            alNPTWVISURzRHRWcmVYUkdnYU1TaFkKLS0tIDNlYmFsZ0hMd3V4THlQU29XdkZZ
            aDdML0FoMzlWemc5VkVKTkJwaXBhQlEKMaxrdXPPDiRMS08DRurpMKSTehsP+JZJ
            VXQJgfCPIYUzIa8wYGKrEBTYliDHdxeBxsmifQqEssL+504XZoNCXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T10:25:01Z"
    mac: ENC[AES256_GCM,data:dFFHb6Tjk4CnYmO7+4RLT2qIJVu5CqDytYzTV1sv6RWJvn7/TfhnEuvSSXCLwLGG7GOREsvH0w41oWISgs+oCA14IhRHLHQwpA9fwhE3709N3ez36rBHi4fDEQWOtwo+em5BYW65AXC5nr0mLCw6VZZ9QtNq+2hTWgLRaKqt+B0=,iv:R9TNOMjkk5ULYsbIsxg0/C2CdcbT5j+EOECDuTKUgxc=,tag:Bn+pqiOX/mFRnCAAFk8+oQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-openshell-pg-backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Qg11K0PBIJu3YO89QhD+E0oqQng=,iv:jNH5Q1akxFdayC5hu5jzJ6cLol7F5tj9U9u/Apel7h8=,tag:20DuRSacvnTWCxTehUnYkw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DMKLF0y9sjufXeLPKItGRklmBSe1KiIcj19CiQyv0f6lcXw4W4mtxQ==,iv:3NtFt4vymJU4AXN/v1s2RpqwB4FLr0zzXcpS3aJTYdU=,tag:dWrh4I7tBNG3gV0LeU/RYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTEpydDU0SkppdzRpcGJn
            WlkrME93MzRmR0xlR0Nvd0E5RmxVdlM5WXdZCm9iMWxzd05RODJScDEyeW4ycWQx
            alNPTWVISURzRHRWcmVYUkdnYU1TaFkKLS0tIDNlYmFsZ0hMd3V4THlQU29XdkZZ
            aDdML0FoMzlWemc5VkVKTkJwaXBhQlEKMaxrdXPPDiRMS08DRurpMKSTehsP+JZJ
            VXQJgfCPIYUzIa8wYGKrEBTYliDHdxeBxsmifQqEssL+504XZoNCXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T10:25:01Z"
    mac: ENC[AES256_GCM,data:dFFHb6Tjk4CnYmO7+4RLT2qIJVu5CqDytYzTV1sv6RWJvn7/TfhnEuvSSXCLwLGG7GOREsvH0w41oWISgs+oCA14IhRHLHQwpA9fwhE3709N3ez36rBHi4fDEQWOtwo+em5BYW65AXC5nr0mLCw6VZZ9QtNq+2hTWgLRaKqt+B0=,iv:R9TNOMjkk5ULYsbIsxg0/C2CdcbT5j+EOECDuTKUgxc=,tag:Bn+pqiOX/mFRnCAAFk8+oQ==,type:str]
    version: 3.13.1
