---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: immich-server
spec:
  networkRouterRef:
    name: home-router
    namespace: networking
  serviceRef:
    name: immich-server
  groups:
    - name: Apps Resources
