apiVersion: v1
kind: Secret
metadata:
    name: s3-immich-backup-secrets
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lt3ljat5oYzVrNxQI1BHTlrrlBg=,iv:zArJDNk4VFfedXatGRJC9tfPgMcWuxXNWHUcWqMU64E=,tag:W+bXGTx5cUBVnZXkm7XnKw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gzp2+QBpg+CPFGRp0cm+1fsux+26x8oaMlEkOw/n+osONf/G5nHtDw==,iv:yS1cu5qW9mt6E8Hpcfg4XttCOKt5OQXypYy84rDEmAE=,tag:32O/f8jhl01jFW8zpO4qUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T14:28:45Z"
    mac: ENC[AES256_GCM,data:LEhu/yLqSGkPb0GiSSOlR6elRvLf9yrFnK/jN8NNin23Sj7If/6Wx5zWgu0UoWqLhkq+DuSzqJ0hq1zSyLdXCSwOOUfCUg5byopDM5oJksgguShz2K/40zz9pwGBPunpf58SQ78047znh2BZNaMpEkNggMIEiuhwI7EUblDxriw=,iv:pkfnE6mpeQ7e6ORf4uZwAvZqx/4vxTTe6jGqybbcfaI=,tag:sEBSYnYY/rAkuNVnuB04pA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-immich
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:GkiDNrDUCKCTCdRF8NZrjmgQ5+XYpRBM3sZ+E963BrAycrA32c07ES8hsJ0XcF3O,iv:8ODU34wfWyF5yrNCvaAXYXtSU3+6d27aEn1fD9sdhhg=,tag:syKxqD6TD/UFBUwXepFu/w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GGkOAk5M5hVWC+m8HMYfJhS1toO6YUQbaZbkpeHSdfYV1z45Al0KpMSN,iv:Iqr60+7dAQktuY5B4dYW5Pew+zbjrbb6iHojqVkvjfY=,tag:/juonPXONAA0ptHna+iaEw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:75R+4Wx05OAOaiyLDwVClKEUIuc=,iv:m+62G9IEZwsZvjuJ3h8pOFEmnknq9Z74HgLn1UfXaco=,tag:oh2v5VLMHRd9GzVUgzmV0Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a5sDxlNkh5QqkTjxJVHmeUsYOV1yNO+M8fhYCehOCjsD9zHS6og0bg==,iv:VpGMcFgAFxPQZdTLR1M8FQYgMP1Xuu5MaP9dJIN8GeE=,tag:Y5NPhdNelm2iimh/JapD1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T14:28:45Z"
    mac: ENC[AES256_GCM,data:LEhu/yLqSGkPb0GiSSOlR6elRvLf9yrFnK/jN8NNin23Sj7If/6Wx5zWgu0UoWqLhkq+DuSzqJ0hq1zSyLdXCSwOOUfCUg5byopDM5oJksgguShz2K/40zz9pwGBPunpf58SQ78047znh2BZNaMpEkNggMIEiuhwI7EUblDxriw=,iv:pkfnE6mpeQ7e6ORf4uZwAvZqx/4vxTTe6jGqybbcfaI=,tag:sEBSYnYY/rAkuNVnuB04pA==,type:str]
    version: 3.13.3
