apiVersion: v1
kind: Secret
metadata:
    name: rustfs-postgres-backup-secrets
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lt3ljat5oYzVrNxQI1BHTlrrlBg=,iv:zArJDNk4VFfedXatGRJC9tfPgMcWuxXNWHUcWqMU64E=,tag:W+bXGTx5cUBVnZXkm7XnKw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gzp2+QBpg+CPFGRp0cm+1fsux+26x8oaMlEkOw/n+osONf/G5nHtDw==,iv:yS1cu5qW9mt6E8Hpcfg4XttCOKt5OQXypYy84rDEmAE=,tag:32O/f8jhl01jFW8zpO4qUQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T07:36:38Z"
    mac: ENC[AES256_GCM,data:ZLREOMZ1ssfx+Na1iGZqGoiCHWsbUDHsA4949Lj1dEzpQjXSKpT5+eVrDwm158PW29Q8pYdFn6qAP5kUaS+8MCCFzCuVLjmg7hqnrKQ6IcIOGmiPvRGzQV5NjSpyFRBt5+W8CPAYvy50mk5uPdK9pQQP2RxgY9WHEY+OjQBDtdk=,iv:Cq6/PPRzxcOQvtnMbgc8nY/PTgdaQ/popewE4ZDjRVY=,tag:zom/nnGrABMMNPqd/ZwwLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
