apiVersion: v1
kind: Secret
metadata:
    name: s3-immich-backup-secrets
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lt3ljat5oYzVrNxQI1BHTlrrlBg=,iv:zArJDNk4VFfedXatGRJC9tfPgMcWuxXNWHUcWqMU64E=,tag:W+bXGTx5cUBVnZXkm7XnKw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gzp2+QBpg+CPFGRp0cm+1fsux+26x8oaMlEkOw/n+osONf/G5nHtDw==,iv:yS1cu5qW9mt6E8Hpcfg4XttCOKt5OQXypYy84rDEmAE=,tag:32O/f8jhl01jFW8zpO4qUQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T14:19:19Z"
    mac: ENC[AES256_GCM,data:axw2Qd6rAwb9AYd/5q90dJRAeKnNsZICINjT5Bpomc9IEoo95gHwQLpRjFIbeIM71rR6hiw0steFRC//A4+KLTNI//5PGiZMBQWFfSatrZ3TRrrFN38EPDAkWI+7nDIukNlXiKvWgKDcbRjbrZE3N5/Xz/s50Co6RrVXd/Pf8jg=,iv:gbfJFw3iuq4CRSNd+qKuqL9Gzvcv7BEWCUrxbf0eANM=,tag:0uWriU4dCyK8v2JpE6zxOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
