apiVersion: v1
kind: Secret
metadata:
    name: k8s-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:pbMZX3Q81YMhegz1eT7inESYW4GJOW0+ufYKMuw=,iv:xvNJv/Th/3IGOBUPCx6RI6UPgwdqrRyHLOUKE99kvYA=,tag:wb0LwC1lakme365FrCZNAQ==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:kz7Zz2x/suCOBIFm1von,iv:LYawZkxtAlip4UFG7hpFv77HGsz663zR7wdLYtTOaeY=,tag:Ynk0cOioPKePgJVCRwpnTA==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:KCXGVm8gwNc0r6qNoPV1PKYw9d/ifPcDGyxJixaNwvF9QFql+GzM3HOHYwAksphJ,iv:aS610akVEUWgGuviPSz6lvrgz6/NfmX5ZvgwUMRNLOQ=,tag:a9/hJR1TM0VFC8etd09hTQ==,type:str]
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#     name: homelab-newt-auth
# stringData:
#     PANGOLIN_ENDPOINT: https://cloud.traunseenet.com
#     NEWT_ID: 10ma90fnni9h1mm
#     NEWT_SECRET: xbgeb3ze43ma39cr1ycche9fkqeovdajafu5rdhdrraz4lg6
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T20:33:49Z"
    mac: ENC[AES256_GCM,data:956OpPQ5ehvVLDCaMLeR1wJgQZti/10MSKGiVg/OjI30+sD6bPUr0M/NArGs4CDcR/9UDmYC7f3tA/K2lf5AY8HGCN2DxtzoWzIEdIrOIBrNWIcPxxZGPDnIlyXCAZDd5WZpTwNEpCQ7ndBRiK6aKiD7hWomo7Zv/4VWecwvrrM=,iv:IKapS2/1DNaUFnDqFAljVmZqk3kFL5ukFKXcHt+gu2k=,tag:LFZUeZvjS8o6S7hN5kJGgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
