apiVersion: v1
kind: Secret
metadata:
    name: k8s-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:pbMZX3Q81YMhegz1eT7inESYW4GJOW0+ufYKMuw=,iv:xvNJv/Th/3IGOBUPCx6RI6UPgwdqrRyHLOUKE99kvYA=,tag:wb0LwC1lakme365FrCZNAQ==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:v5NFgVaWM7HZWdeDATA2,iv:WjqRKpEjbW7A3jZuaqub37S/YpmuRhJ470BlEW9s6G8=,tag:BfljSlQZukstWCODdqwa9Q==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:iH7rqa0Yzqpw5HzyALEdY+xK+d03ybYfvz5Pt6XO7bzR9OW5asIHi5BCz/XplRc5,iv:7Jcif3V6x9a/VwRGLOp+Gmm7dky4Mwk1ppPzylIqksE=,tag:55MifBs2+MeD8sWxIwRg9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T20:07:07Z"
    mac: ENC[AES256_GCM,data:vewRVFNm8NoEL89eN+wuIOiZsCWH0tfvBFORvu93bNJmzk1t186dnOL/KF5pCvn2TVIu3Zx3ALvEeTxg31EZ9pNMjKa8t//OX7cOxUAfzlrWGtIyc0b0rIcoVyg2SI+IscjdJhFtLF9BJf/ysrKLPIKOHT6jgXGdVYRCRmzJjmo=,iv:fQbvrDBlWOe9F0a8chi4dfvG+T814agO6mmurWaWR/k=,tag:gvGhX1nStERXWop46FZ+Rw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: homelab-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:pbMZX3Q81YMhegz1eT7inESYW4GJOW0+ufYKMuw=,iv:xvNJv/Th/3IGOBUPCx6RI6UPgwdqrRyHLOUKE99kvYA=,tag:wb0LwC1lakme365FrCZNAQ==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:ZtYvVTvIMe8W2ax3/uXA,iv:VZsCNogn22iWhT2qbitrTPQIFeurdMGt6RxFH8JEuDo=,tag:6stRZbX7yCEe0RcvYlY5aQ==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:RFhaIyH6Fi5J1OIWBMg8m92XXxDllouJtHGmSEE/ktKju8Qu1gHNV1bIBrBOCDsr,iv:0i/B9fdznx9E3xzj7loD8sYLT6YzDUxLk04y/F7bbUE=,tag:Fcw0zCnsuAoXHkKf2WmHvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T20:07:07Z"
    mac: ENC[AES256_GCM,data:vewRVFNm8NoEL89eN+wuIOiZsCWH0tfvBFORvu93bNJmzk1t186dnOL/KF5pCvn2TVIu3Zx3ALvEeTxg31EZ9pNMjKa8t//OX7cOxUAfzlrWGtIyc0b0rIcoVyg2SI+IscjdJhFtLF9BJf/ysrKLPIKOHT6jgXGdVYRCRmzJjmo=,iv:fQbvrDBlWOe9F0a8chi4dfvG+T814agO6mmurWaWR/k=,tag:gvGhX1nStERXWop46FZ+Rw==,type:str]
    version: 3.13.1
