apiVersion: v1
kind: Secret
metadata:
    name: k8s-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:pbMZX3Q81YMhegz1eT7inESYW4GJOW0+ufYKMuw=,iv:xvNJv/Th/3IGOBUPCx6RI6UPgwdqrRyHLOUKE99kvYA=,tag:wb0LwC1lakme365FrCZNAQ==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:L8BiAAcnytj9VXI35Kz9,iv:20fVLm4U3o86zZDP0oIyFv+doS90wTazebg4U62Er+Y=,tag:3v3GOt7JvDTT6ruNzutndw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:8saDZDA27MygRU8w6onnP1SdGQKgQnCYhhTvnFVUJ6MsJnGGGa7Zbs9jSLtog8iE,iv:CL426dgG85xJ/dFP1Xx18Z97Fcri7e7OWdrUzq1PVEg=,tag:6Qgr45pvErmIfilk1bQIlA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T07:55:02Z"
    mac: ENC[AES256_GCM,data:zmUB2Fq7s5900ZuhVfavn2ZPJpNmP6UB4v6ihzuFXh+6JmUvAipFRTuBvNrMgNXBEEr+Gx0uECOnxkHPbAS0bB58COzrjWFMWLg4NBccFE3KnFBwJ9M80bCSXrLmv/Tu+vOzxKZenk3y7kB0f57kKK03EtOzXL5dFTPOIa5g3vE=,iv:H3ltKtw64UHnKtmVpvfXr5uY3gGz67apo5tbkKWBp14=,tag:wB9R3RJjamU5081t5aQABg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: homelab-newt-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:pbMZX3Q81YMhegz1eT7inESYW4GJOW0+ufYKMuw=,iv:xvNJv/Th/3IGOBUPCx6RI6UPgwdqrRyHLOUKE99kvYA=,tag:wb0LwC1lakme365FrCZNAQ==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:PgH8fBwmk851FR7Qt97A,iv:U6K71yxZrqXYZIH7pC59qbQbgPsns03Nui8c2hg6qWo=,tag:GIDw1Tmsn5AJI0UGnmOllA==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:agkkE/nsyqjq9tgX9kWhSEEoIPsAvyE3CTVxb2/v5mX1W6TC9lsmbEUrkImw4OAH,iv:ieZrnblgMY88mRY8Dlo6YbuQnyjpuFM8PEWJaznkhtM=,tag:zZVFcr97N5Jwvh1krl9tbw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T07:55:02Z"
    mac: ENC[AES256_GCM,data:zmUB2Fq7s5900ZuhVfavn2ZPJpNmP6UB4v6ihzuFXh+6JmUvAipFRTuBvNrMgNXBEEr+Gx0uECOnxkHPbAS0bB58COzrjWFMWLg4NBccFE3KnFBwJ9M80bCSXrLmv/Tu+vOzxKZenk3y7kB0f57kKK03EtOzXL5dFTPOIa5g3vE=,iv:H3ltKtw64UHnKtmVpvfXr5uY3gGz67apo5tbkKWBp14=,tag:wB9R3RJjamU5081t5aQABg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
