apiVersion: v1
kind: Secret
metadata:
    name: restic-n8n
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:XXej/4mlrcYXMymKw9k4ErMxAleKgkqQrVPwBLvQKvDiRNik2O56TcYvQe3G,iv:aB0EkTCIT5xuxJrTD+GWlnq+hcU3JFNk0ZQ5ckVYOck=,tag:RilSZZFWd0ln/BkCha4GDQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:IXj30+0MzCnGirHDsxkTVNdBoKQ9M7zjDSKuRXcNdNKf/MaJUCGodqQ=,iv:DuyNLQWpVW33kKUIbXctWF6Q7alaWIlGK5aoT5S8Uqw=,tag:7pXgaRdqTSNnSTYh0NZgbw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T10:12:38Z"
    mac: ENC[AES256_GCM,data:AZU/b1ADfIpnCVsmd+cQEbrna5bPzQMatI1Nc6RNmoNhVs24aqnrtLO5FqOHL5zWooFxDkvbHrOxFvxf74+3vJbUiYJSTnafiBq82XNwZ4QiViJU/CzSawJnk2FenIbVRyxXBj4VpEJF9hGd4UEXpz+5tMetMQ0jEsDq2hi/7N4=,iv:M9N2yXbVUQpdGHJag7XG8Tgva+32bxjOSG0LQgQgRPU=,tag:if/zBGyrMcxlQ3O1c9ZyZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-n8n-pg-backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hXJjWTttitZg1wy02bcJhcx9AMA=,iv:yit2T99IlrscB8qES+74GUTWcadFEmpm0WOL9RoHRrY=,tag:k/0ukdsQTZj9kQxnzFTTEw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LUW3e3rDcfHTuHXPURMXfzNL7gk14nKCJjAU08o0m7WmHOMRJc2wfA==,iv:IgkZSlR4eJmr87DFE+TQVDOO2c60JLqnHkOHMb1hbb4=,tag:JJFsaO+vpQFA3aOdt5f1nQ==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T10:12:38Z"
    mac: ENC[AES256_GCM,data:AZU/b1ADfIpnCVsmd+cQEbrna5bPzQMatI1Nc6RNmoNhVs24aqnrtLO5FqOHL5zWooFxDkvbHrOxFvxf74+3vJbUiYJSTnafiBq82XNwZ4QiViJU/CzSawJnk2FenIbVRyxXBj4VpEJF9hGd4UEXpz+5tMetMQ0jEsDq2hi/7N4=,iv:M9N2yXbVUQpdGHJag7XG8Tgva+32bxjOSG0LQgQgRPU=,tag:if/zBGyrMcxlQ3O1c9ZyZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
