apiVersion: v1
kind: Secret
metadata:
    name: karakeep-mcp
stringData:
    KARAKEEP_API_KEY: ENC[AES256_GCM,data:s3N32z1yNPEsob0MnlJxEenzY8fYBghopyTMvMij8Wfcz/rtC3SaSfS9SeCm2h5cQXXbAwaet950,iv:fxgZc5q5dK9HH7CFooNw0p6e9ZRZUlmlQQZWsyLxr5Q=,tag:i8raa6qQ9403zyH+9vxd9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T10:10:55Z"
    mac: ENC[AES256_GCM,data:Fs2g+OTlGwDGoezQWU78GGN871E8PO9Nd8qtaeG1VT0EMjTd/ZuLTYLFB928GsLld5mG1tJrbIZabFjm2x8p5oWdsMoPMuyL2dZ+FYoz87rTWVYTx2DRMpBDS3y5+kyjBIMLeIaatEfvOjkOLLJDksgT0WhAyetI0ZvbpUs3yoM=,iv:CZ/s1H72gw8xOBKrMmbaJBm92yWk94eOGJwkT3B/zbs=,tag:ex/1I2D87OhvDgDRmlUu/A==,type:str]
    version: 3.13.2
