apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: karakeep
  name: karakeep-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: karakeep-restore
  resources:
    requests:
      storage: 5Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: karakeep-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-karakeep
    storageClassName: longhorn-storage
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    capacity: 5Gi
    enableFileDeletion: false
    cleanupCachePVC: false
    cleanupTempPVC: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: karakeep
  name: karakeep-meilisearch
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-storage
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: karakeep-meilisearch-restore
  resources:
    requests:
      storage: 2Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: karakeep-meilisearch-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-karakeep-meilisearch
    storageClassName: longhorn-storage
    accessModes: ["ReadWriteOnce"]
    copyMethod: Snapshot
    capacity: 2Gi
    enableFileDeletion: false
    cleanupCachePVC: false
    cleanupTempPVC: false
