apiVersion: v1
kind: Secret
metadata:
    name: restic-karakeep
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Yu4/aKcOzNW02bj1GPL6gTe1uBFf9vDI4v25dw3wanCgRfmd5Ms3VgM0I9Ow5AZzPkY=,iv:fq4d6E4KN5fTy4UjgjMyIIlXr4u7frPThvcCRiQgt0A=,tag:NwzdoiwaJ4dMQahKUS+8Bw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:oq04TQ5gWH7m7FLaeEykcwUiujuF6fS9VgHoHfzCeXnVmiAFquC0R9b+CFDu6ns4my4=,iv:GCvuGfSi3vhKgDtKS7qP1tVio+bulfKY/HiMh0xOt7M=,tag:I0FhhFCvEJ4vlShIKgu4VA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T05:52:51Z"
    mac: ENC[AES256_GCM,data:4e0KWqKcXyIw5IAyyKxRAoDsL7W8i3hTOJ78CHdK9EbxjuqORsi//lb+S1ZTbxuHc3+BSsYMhkulhhacGbrNZ+G5n7+yq8+MTiidD4qYd/Jhf6U/eUbJtoVXHCpI4MNP+ZSgVakDQ3wWAPXfzZRv6NPXfiVQMfDTM/KrpLV80ZQ=,iv:80aqsHMHmrImf/XDcuZwamKZ3CVw+Z4vb6HtVtmCZTU=,tag:S66bcIszit4NDhF9ynU/wA==,type:str]
    version: 3.13.3
