apiVersion: v1
kind: Secret
metadata:
    name: karakeep
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:YRIat1KS2GsoD/o7lA91KPARA/TE0Z5x7RXTmJCSk38vprYTKsUQVT5Q3bcFqf35,iv:iJo9fSKYMogND/iugOI3vXRG0VCVTjU+wqAF/CLwrsk=,tag:6l2R43jTWSA7HGkVWMjucg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:N779znb/ih+uZ+FT2deMN0UNXEVqD9y8HJ8ormHQrUlasBZLrY/J0OxaUT4o48LT,iv:isLfn05wueuj3HFGWJS2m11fWiK0vlZn+ilO4ceFqO4=,tag:vwgN/QiovrFP6IC7aUmjQA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:L6V66jE=,iv:T5+uH2LnqmkRbHfHEnBAddfVqlbnolbeQ00uZKXJTmQ=,tag:c0SUQA3zW+N9RafmCH+5kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T05:32:59Z"
    mac: ENC[AES256_GCM,data:Ek9NxDBX5QuaYkyHL/xsSgTWmMJfHlIBTmb/in4heSbjQ3P0fRPu1SLVP9EIMfmrbuDw7rAkciHTZNasxSE0ASy4joozNDujyQSOgTTRNagg18k0/7wgnWeZE2lwD3l2GRpOwNblBQz8eUIQGQ6fjqAi2y/FE6k00TSgQMlKk7Y=,iv:IGGtWaMMPTeBEim9iAgID6WdGqCCZ5jVYkfHQXQjnks=,tag:nodY8LqBtId48K8bqsoTkQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-karakeep
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:YraUsOqw1Ex/E5VekuEzhPSWF2S0k8XvSNymycLaKiofh4LW92I9WPse,iv:A0A/FSobn5wbDOkK/L1PXYw9ao3NpbJa4DEsi7Ve+M8=,tag:kvqqp6pcjUmYuldhwTVWEQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:oq04TQ5gWH7m7FLaeEykcwUiujuF6fS9VgHoHfzCeXnVmiAFquC0R9b+CFDu6ns4my4=,iv:GCvuGfSi3vhKgDtKS7qP1tVio+bulfKY/HiMh0xOt7M=,tag:I0FhhFCvEJ4vlShIKgu4VA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T05:32:59Z"
    mac: ENC[AES256_GCM,data:Ek9NxDBX5QuaYkyHL/xsSgTWmMJfHlIBTmb/in4heSbjQ3P0fRPu1SLVP9EIMfmrbuDw7rAkciHTZNasxSE0ASy4joozNDujyQSOgTTRNagg18k0/7wgnWeZE2lwD3l2GRpOwNblBQz8eUIQGQ6fjqAi2y/FE6k00TSgQMlKk7Y=,iv:IGGtWaMMPTeBEim9iAgID6WdGqCCZ5jVYkfHQXQjnks=,tag:nodY8LqBtId48K8bqsoTkQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-karakeep-meilisearch
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sUn8SLji7tyZCMLe16wJOmmXLxcrQebzwB/M36ZFDk+Ap01F4O6AzOrP6Kln2mlRzHaBeMr5,iv:v6aq4RNB4+6UzU5mqSd2pobfSCYTQplrtQrmDdT3nis=,tag:YgWMf2Q56dk/feu70qubiw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:eWrGgHdrX7V9imsohb8x9oc3z3huyuPHCRuD2VqbAYj8AO46ZA39FMYCqn/oozhy,iv:CWfMd3CTO7IJfKnG2XyUXleaA4tkU6XBmGJarZftYfc=,tag:vfzq496Afv83W557YN+7Kg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5lyKKhlytf+hQt255pEoUHmT++c=,iv:rjy14/M9/ZyyTb8Bv7lttN/lW6A4aWc8vhkY9UsqfNw=,tag:YB40AXhbynCGBSH7MdRsRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u+V4z8F6UZp6xIG8mdWM7XYUTzR+zIf3shUCOHEKSdk5NGyT56tXew==,iv:LCDJGKoKeJjFzJ2a56PwiEyMs3q2AaGySI03cHuXLdE=,tag:QSlBah0KYhQUiCKjPOd5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T05:32:59Z"
    mac: ENC[AES256_GCM,data:Ek9NxDBX5QuaYkyHL/xsSgTWmMJfHlIBTmb/in4heSbjQ3P0fRPu1SLVP9EIMfmrbuDw7rAkciHTZNasxSE0ASy4joozNDujyQSOgTTRNagg18k0/7wgnWeZE2lwD3l2GRpOwNblBQz8eUIQGQ6fjqAi2y/FE6k00TSgQMlKk7Y=,iv:IGGtWaMMPTeBEim9iAgID6WdGqCCZ5jVYkfHQXQjnks=,tag:nodY8LqBtId48K8bqsoTkQ==,type:str]
    version: 3.13.1
