apiVersion: v1
kind: Secret
metadata:
    name: tsig-key
stringData:
    key: ENC[AES256_GCM,data:vx7uVYZKsZZWFja1SaeNSuW94nOC+fKesY3i854gbHzMRajWqZL9kvWqUqV5Q5wzJk6sOZi2Mk0lkQ3uL7InwA==,iv:C1rZjhGu54RwIMZ4JjBrlHf7we98sCu5gdXWEATYKwA=,tag:OXorEy8GmBqUort8J1Km2Q==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T19:21:35Z"
    mac: ENC[AES256_GCM,data:C3wiQ3eCE0Lu8yF1UC5LXcUQCN11xyjSOE00HYXMZ2qv9sy96ZMA33skwSdnCE7zog/rA8yW/ufcimegmzGykq8Cmtf9GOMB+wR65BOkAKs4DRWTeLy+RN5lAWEiqV1tIB/SY9Ahi8PxFkaF+iVLcHxcY6qqpUDjA15bTFAVZw4=,iv:f6xwNZF/XymekDUjxBVfVCTTRAG4hj98L5V6zhtpPe8=,tag:7DcKQHil/O/CJ0khjKM+Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
