apiVersion: v1
kind: Secret
metadata:
    name: tsig-key
stringData:
    key: ENC[AES256_GCM,data:O2wA4/mNu3qoLmrQ9QoePhoOshvfAQxFfhM6kDVvR9mYhqvS5AApg5aFYhY=,iv:saAjE/dlwGu5i97yrX3mUwP+GpGDKgaVnnCIlnl6jq4=,tag:IyP93M63kB1ywxFKBP17Cg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGZzOE1IVUx3OHVsckNu
            MlBjY0FYZktFb3krQlNGTmhOREUxVVZzVHhzCjh5L1djajA4TGF6OUh2eVFQV1gz
            YmJIL3Y1YWRpd0h2bHRmQmZmSU5jamMKLS0tIG5IQW9LRXV1T282NkhhdGw5dlo0
            QnFLeG8vNUFPRVNROWVod1ByQWVGSEkK0lpF0B30ZzKqE6rFR3K/WQZoscManSzu
            ds0Nj8kXMACkSQ8M1rEUa211An+iDzlxRbB7Yt3TzG04P9i6NvycOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T08:37:51Z"
    mac: ENC[AES256_GCM,data:Yv1e/qUI48dvImSZ5IBVsrVS8OyIzRJIiWm8/xcOVaQ9vxkrrL5/yK/AylOclSefHAS4AJ4bXzGjZznO0g4Se62y7+bxHCA53Ayc8dCEGL9TSlDmhc4MGjAOdLKrhvY5chr8bmrbuO7uBrOpWsPfbI9C5Gsuj0jPYkEHJlZZBAo=,iv:MF1B+pWRBogsVp7GmkAa+H2Myz+8uCbS6CrBnEmkKAY=,tag:TxuotnUO6J8bC4+i9dMN2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
