---
apiVersion: v1
kind: Service
metadata:
  name: navidrome-dns
  annotations:
     external-dns.alpha.kubernetes.io/hostname: "navidrome.cloud.traunseenet.com"
spec:
  type: ExternalName
  externalName: 10.2.12.201
  ports: []