apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-env
data:
  SEARXNG_BASE_URL: "https://searxng.cloud.traunseenet.com/"
  SEARXNG_LIMITER: "false"
  SEARXNG_IMAGE_PROXY: "false"
  FORCE_OWNERSHIP: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    use_default_settings: true
    general:
      instance_name: "SearXNG"
    search:
      safe_search: 0
      formats:
        - html
        - json
    server:
      limiter: false
      image_proxy: false
