apiVersion: v1
kind: Secret
metadata:
    name: searxng
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:g4Mk4bmp0iVr+zXF/MNeoOhog5b0hzyAqydYF0XTN9YnFR4Hv9eJhixVmFngBxF+9F2Wo/7RFZgF+Xq94aVhTg==,iv:hXRdW4QbHzPd3tDggLTC3ppVbNQVUZ5IF6Wb7oSpTwI=,tag:B1vFJkbHyRr6U+WfDKseRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T19:34:12Z"
    mac: ENC[AES256_GCM,data:TyQI+kbYK3+wwFADMc05ubjOWW+YRByRq+EwbdQoUTjj79KtbuURVoT3lG59otr1xQS5Tf+YYj6bA2a4f2RxLZgEnh3BE3WwR+6us8MBP+zvdn13POWePYGcY/2fDRErL1OjfyirHk0rAPZnnC/NzB9xwrDQxdECbnLtS1GqS4M=,iv:+vTST9SONb/eo21eJI9hSXJhTN36pkJLBiKqgTCuRnc=,tag:T/lftZZv3aEom15mojcsjw==,type:str]
    version: 3.13.1
