apiVersion: v1
kind: Service
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  type: ClusterIP
  selector:
    app: searxng
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: searxng-mcp
  labels:
    app: searxng-mcp
spec:
  type: ClusterIP
  selector:
    app: searxng-mcp
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
