apiVersion: v1
kind: Secret
metadata:
    name: trek-secrets
    labels:
        app: trek
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:kIbf2I2uoVfAuqW1D5MxNVifPdox7D133RF1iRY3PhzWYFRRZFENbjBq6xpLk1pJ17bSalZhSNPtw5kbC2mYcA==,iv:kTz6fMtvegOuhG6fsJDuT/k94CxTgjjYZ638rckFQ50=,tag:Jjfzp1uGTu2Qdz4l70gnxw==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:eGSLoUndn91bhddQdtEUT+Kb5ygvO0M=,iv:AHrs+exoDrlA9+okkzURmz6y1TAqtbQMoHm4WMGw/78=,tag:JBPEevlMGNrTBdWrgz2uFw==,type:str]
    #ENC[AES256_GCM,data:APJw/tH4pK5i+zmm5O2mqqQZCrgH/ImLfpPssuJxlmgJQk5huEqsqJPvSCFa5UqCQM3Vyl43wA==,iv:wJvb4NKfZjs7JAeaJknoYdxcKhN8DiXXwZ/Qq2ShuQ4=,tag:kVde8pMrHygvVAYU/HnLhw==,type:comment]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:S83hcQ+QaxHG668FlLOHIXK0Z7Y=,iv:N0VEkaM66biKbZfupJsIjt4XnBQsaYOMvmp0Y/45bLM=,tag:h428K4T+qCRbD6oNq6xEOQ==,type:str]
    #ENC[AES256_GCM,data:8QHRIo8UiRZY/Lb6lbQQbUXl56SjRmDe3izOt8ag0XyrzTR5M1HuJ28X6fgX7TNqHzAs7NSE09akjSSWvGrsmeRqiUOctPsp756gWQ==,iv:WxmIZJDqWVm5Bm5GFqu9dGuNUQirJPt2jXjB0jXWkt4=,tag:Zh+68j2UtuFCfaZ/58ANzA==,type:comment]
    #ENC[AES256_GCM,data:T4lvfIi16XYYQe4WGUP+5sUUNEJjoGmeskiq+Ye5W+2qNU3TNH3IpuLg441rhw==,iv:Uf8dIOOMwbYjHR8m7duKXWPDeoFIw6HjKfc0i1VCx2k=,tag:7snNMXPFP8G+yirMI1PCzg==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:n1VvxA6Ykxo6qOB7jt1jkD+n+W88VdXn5IE0R5jEdVA=,iv:TbhioSoXyEIJUA+/CKJl/AOu6s6xZySpmReesoUQrXo=,tag:oaJdc/DDVvN/3B4+ZqFtuw==,type:str]
    #ENC[AES256_GCM,data:Yo77OtSK8Z8P/z89GXyht0uz8skEBlKJCiNcBDtUo8UNLkZfMtJa5z9Ml/WcgLE6LakM4HUAEG78snmIQHj+Br5xlbvd+gFpM2Zn,iv:mYJZqmMgVSsHwsZSs55bonDorBKt7wDXtxXzXRckqZ8=,tag:am45ORwXGKPcEU6bqTZVAQ==,type:comment]
    #ENC[AES256_GCM,data:5qMHfhtz5/8/Lk3MhtKQvSwMmCviA29xEXF1H/Z4RROYQl8SkHW1DxwsWE+TKwYj+21wGvNBHmwA6Uwx9LJBS9cprPaBRbk34YIZDg==,iv:ILcfPBQAh6JW7E5to2/5VU55Q1ZLgDUOIj+xSVtBAxI=,tag:b0b4eNF+wMqvm7BGGd/ybA==,type:comment]
    #ENC[AES256_GCM,data:AT/c6rA3Rj+UAgv4GT48l59b7/Y5i1SVDcCjyHb61xdda2euPwquE29qnal6G/j+GknY/QLSRGk/FAFSizty2OISXhln,iv:oQzdgLfFnLu+PoUOiX2wfmWmIuMeTGw4b+xsOh+Qgiw=,tag:9mXB+ieJCxRyTuEX1kT7Pg==,type:comment]
    UNSPLASH_ACCESS_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNGwrMFhHSEZLaHlKdm1z
            RCtyWjFoS1pGVWR6Q0tLaVFRajdyMW5ocEVzCnU1akRyNWlmcTdPOVY4TE02UnA4
            cDYwVFBVYUo1bHN3R2phOWRkT0hwL2cKLS0tIE5Talhqeml4Mk42aVJmS3BBa0pB
            RGQ3OWE5SXA2b095MjF2UzNhWC9PS1UKIeIeEpWURfyFfZ4uxD/btYF3qhji9zy0
            VbYr0/nWYUzXIGJWeJFsC++1Y5Eew4LRC9mbQIGn//dXcXNt/e7BxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T20:43:49Z"
    mac: ENC[AES256_GCM,data:zNwSP9xLh70UPozNJF9uvC7Zzc0T6kjMGlbPhbPBZGGFYNrSGUAyebj0nWO7iAFXZqbcG75RUpbhWyXt1ny3znulXhAO+mj37RvQs6zTcpsFuYf2kZjSrAlu8IVEIeD6IHzNtpgkkrLKc+FiDlZsan9GPaY4IOCMza8RYw3V5Y0=,iv:6DmvIwrOrgAKL4BjhwxIdTH5MaUDl2kS3ohRJMwc2Vw=,tag:0VTDIA5lQ67hZQ1kyhZf0Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-trek
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:LHpfl3J/+DPAxXeDLOz4IRqkHsu4ay664CM063AE5X9BXZWLIQlXGSAj/s42fA==,iv:sL/bg76sc6mWNozRDy6fNjEO6DKrm0Z2n+ebaEGACdQ=,tag:Q5DOifWS1BVaRlV86K7pEg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:XyI+Pn+LWzlxOu9uAcok3BlD/ahJzVkRSgoGhgkjNVQkNVl7uwK3SXusu2mqSNkh2PBOMOwj,iv:wFDWDu2aqnDPisn8BzmwUk6hFKuTGf5t34X2G7KOVHM=,tag:ctEM8h75FuyLx5QnwiqhoA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+GSMUjkOHMQKSK3CiNTyRDZk5w4=,iv:ehNBUQLSochYoI/HeLaurcej4VALaJvtkMboCgLHmtc=,tag:kI7kVhwsvZE1U8hqSCm4cg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KbNiVDWtgLnijHQxrRu4wP4tPMAZn+Gr3cZmcZJtRvDmioz9NxOrQw==,iv:sk83anZ8t7Poil4YNZtH5wawwlxmpbYMqT2nKXebkEw=,tag:7ndeL4tk6wEAmj5hvzCrog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNGwrMFhHSEZLaHlKdm1z
            RCtyWjFoS1pGVWR6Q0tLaVFRajdyMW5ocEVzCnU1akRyNWlmcTdPOVY4TE02UnA4
            cDYwVFBVYUo1bHN3R2phOWRkT0hwL2cKLS0tIE5Talhqeml4Mk42aVJmS3BBa0pB
            RGQ3OWE5SXA2b095MjF2UzNhWC9PS1UKIeIeEpWURfyFfZ4uxD/btYF3qhji9zy0
            VbYr0/nWYUzXIGJWeJFsC++1Y5Eew4LRC9mbQIGn//dXcXNt/e7BxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T20:43:49Z"
    mac: ENC[AES256_GCM,data:zNwSP9xLh70UPozNJF9uvC7Zzc0T6kjMGlbPhbPBZGGFYNrSGUAyebj0nWO7iAFXZqbcG75RUpbhWyXt1ny3znulXhAO+mj37RvQs6zTcpsFuYf2kZjSrAlu8IVEIeD6IHzNtpgkkrLKc+FiDlZsan9GPaY4IOCMza8RYw3V5Y0=,iv:6DmvIwrOrgAKL4BjhwxIdTH5MaUDl2kS3ohRJMwc2Vw=,tag:0VTDIA5lQ67hZQ1kyhZf0Q==,type:str]
    version: 3.13.3
