---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: jellyfin
spec:
  networkRouterRef:
    name: home-router
    namespace: networking
  serviceRef:
    name: jellyfin
  groups:
    - name: Apps Resources
