apiVersion: v1
kind: Secret
metadata:
    name: paperless-mcp
stringData:
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:t7Ae+GsSISmvEL957dhnIg7OAAVJhmV+EomWF0Silt1OOl061oEiKA==,iv:8zt2p13guG4OqibV3N2pMb9ufQg+VWK1Xh8EphwilBY=,tag:Wd3twzNnlLCo9n8R/dI+vQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T05:17:37Z"
    mac: ENC[AES256_GCM,data:EliAIlpbfc/V2VRqrL3+JecT2SwBe2TqQBOXl2pJpXdW+rFU7RHvdruW0Uye2teGsl6o2I54JM6Q7zZCDUvKc+4PIc5jqeAsg0ZIUA6/jSQWehBUhjdsT50eqHTQ3IYmwcOrohA0SivQj+z3WtDrSta4Z8EbNW9oWcNOwvuihUE=,iv:VcJe70s9CdluSXVc/eox+fD38O7ebFTX5t5oCOjTuic=,tag:CAJf+5Hm7Y1SMW06j/fP9Q==,type:str]
    version: 3.13.2
