apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lCl+cAmY1T3A2uM2ZBAD8KlJrD+rz3fzsUDytva+lrf1pM8M,iv:o615GVGANd9s+fheUeYAJWzdIc+SMoVnkAalM8XMeYY=,tag:CIf9/mpiEH7BL6fxwWypWA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4eKDTh/AO05FVBvchsfA8eq9R52voIlS2dLgcLhvAm0=,iv:Yz2hWSogA2/PRlTZGf8L+AVF9vR827GFsObJYbtGLe0=,tag:ij0BIJJ/Dp5VAA4KaoF9jQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:1+ftRGq2CybRG65bZmmTMAY=,iv:dwleC2ZQfU16g967cwYCIwA5/OYd7mXyUClxvAFvlv4=,tag:5QqYFFrl3FkhskwMvMiuTw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T10:59:11Z"
    mac: ENC[AES256_GCM,data:I31KguKKctUAXVA8gmWHCsy1FzGF/833tO9TwP2jkg/SYmpB3Zv40n6UMjfRxXXRMl2cDsehVJCnkC8mGmlFY+gmFr/b5Q9XBvt1RFZUGIr0fyhj/2Q4AjNk8/T2SF5/WZzmQPmtMIB215aLPTQ/bUkvNb0bfTSqhN5nXqdj6XE=,iv:XskAEV9tmZSohpdtf8aW0dmZPP/vEy1X2VJzK3jodx4=,tag:Cw1abGWuFVyvLHP8Q5DhhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-openwebui
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:HLracBiL63eZIADz1OEh8NtAdNdpIeu3/EuAP79fuOzNllGUKvnD1vhSsszaVSG+d+aH,iv:YyJB242bCOpWS6MjaeglHdasEZNeNcjPqg2K4TGh/0g=,tag:Q7kNGSz/jW9OdnnVE4xKjQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Hv0Yw3uJMAZ/nMVjQsUGUWE9Tuoje7BoHYhu2RiBjVduQPSbh4shfEoR5ERh0W1/cgk=,iv:k9mOUp3uHaITF18+apnQoPZ5CmVpRE14odDOnlZrxYE=,tag:6V18k3EdWfwhKR8AJLMVWw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:k9AF2tjhV51aBbCWSDC7FToUIZc=,iv:/kih7OnrocWGgF4n1O0bXPpBnaZylx8pxDr2Uc+DpPk=,tag:KNsMCKa5O4qjA0S1GA4Igg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aadxUDb7ciwPHY2iJ1WzH0qDsvIbS5upK0CvTJ1qRbvizabTLBkd/g==,iv:wIFhj9ZDDkGwwbhewtafGZwIAwAyek+Y4SFPjWjI7NU=,tag:lQ0tTistsRmyLiRzNlA3Jw==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T10:59:11Z"
    mac: ENC[AES256_GCM,data:I31KguKKctUAXVA8gmWHCsy1FzGF/833tO9TwP2jkg/SYmpB3Zv40n6UMjfRxXXRMl2cDsehVJCnkC8mGmlFY+gmFr/b5Q9XBvt1RFZUGIr0fyhj/2Q4AjNk8/T2SF5/WZzmQPmtMIB215aLPTQ/bUkvNb0bfTSqhN5nXqdj6XE=,iv:XskAEV9tmZSohpdtf8aW0dmZPP/vEy1X2VJzK3jodx4=,tag:Cw1abGWuFVyvLHP8Q5DhhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
