apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lCl+cAmY1T3A2uM2ZBAD8KlJrD+rz3fzsUDytva+lrf1pM8M,iv:o615GVGANd9s+fheUeYAJWzdIc+SMoVnkAalM8XMeYY=,tag:CIf9/mpiEH7BL6fxwWypWA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ocZ/L4qsg4V61Ibj0/9wzrqsBYkEuZ15DILs4XReYvE=,iv:PaVj9iuuHamCGB8KYJ5w9GQ9+ybJMymxDm91mch4rUQ=,tag:CjRaBzgweq6E2bSuLYaHhQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:OAhHP6PRzZEcZVStjyizn8rR8CwEPU/1HNNMf/FPMH0Rz4vC2/aEDWZv,iv:chT1+On0FL0SSyqzGP7NzGSdoAghUHRz9IFvjKqanPY=,tag:nsYLwuSTk4c/Ch9PKXKCOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T15:54:08Z"
    mac: ENC[AES256_GCM,data:mjhURY0Jl6t9zhSjqIhiGvpEdj+cf3CzoDYdWiFaT5g74tdbCL/VRN1y99RNXKeA5Ch2HixxuQ3IZ7WKIS49Lj4eQ9P2vJinpXRzLMyIWFXPeNCGSme5TVy+7qGFL9NHkpz0XajIHrQVtaJ/ho9whbxh2LwF5dOd39Yt8k0y6bA=,iv:lHibtG1QA2coJQ3vU6MwbUAKd2LMbWU/Ofc3w8EJIn0=,tag:zFXzCvpM1lyhqLw0WIY3+Q==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-openwebui
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:HLracBiL63eZIADz1OEh8NtAdNdpIeu3/EuAP79fuOzNllGUKvnD1vhSsszaVSG+d+aH,iv:YyJB242bCOpWS6MjaeglHdasEZNeNcjPqg2K4TGh/0g=,tag:Q7kNGSz/jW9OdnnVE4xKjQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Hv0Yw3uJMAZ/nMVjQsUGUWE9Tuoje7BoHYhu2RiBjVduQPSbh4shfEoR5ERh0W1/cgk=,iv:k9mOUp3uHaITF18+apnQoPZ5CmVpRE14odDOnlZrxYE=,tag:6V18k3EdWfwhKR8AJLMVWw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:k9AF2tjhV51aBbCWSDC7FToUIZc=,iv:/kih7OnrocWGgF4n1O0bXPpBnaZylx8pxDr2Uc+DpPk=,tag:KNsMCKa5O4qjA0S1GA4Igg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aadxUDb7ciwPHY2iJ1WzH0qDsvIbS5upK0CvTJ1qRbvizabTLBkd/g==,iv:wIFhj9ZDDkGwwbhewtafGZwIAwAyek+Y4SFPjWjI7NU=,tag:lQ0tTistsRmyLiRzNlA3Jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T15:54:08Z"
    mac: ENC[AES256_GCM,data:mjhURY0Jl6t9zhSjqIhiGvpEdj+cf3CzoDYdWiFaT5g74tdbCL/VRN1y99RNXKeA5Ch2HixxuQ3IZ7WKIS49Lj4eQ9P2vJinpXRzLMyIWFXPeNCGSme5TVy+7qGFL9NHkpz0XajIHrQVtaJ/ho9whbxh2LwF5dOd39Yt8k0y6bA=,iv:lHibtG1QA2coJQ3vU6MwbUAKd2LMbWU/Ofc3w8EJIn0=,tag:zFXzCvpM1lyhqLw0WIY3+Q==,type:str]
    version: 3.13.2
