apiVersion: v1
kind: Secret
metadata:
    name: pangolin-proxy-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:IItEePHaPTbzMjzC/5Gt4IZB0n6J8bZFrrS3IyE=,iv:C+h/U1XMJugRUpX/MICHT6lXo7i3CGRK8BE5ytfw/1o=,tag:ILuBgvvVN5YFRJVotxOqKA==,type:str]
    OLM_ID: ENC[AES256_GCM,data:P2oi0pf4TTz+eN1OJ11Q,iv:8JxFeOX3xAAXVVzY8/m7WdU7P5FnN9GTJXYytuwQokk=,tag:InOHuQSTlDfxgs3aUPs9mg==,type:str]
    OLM_SECRET: ENC[AES256_GCM,data:ZPju/xyfMmT+yGuT0UWZLn4aa584/swhcsTKZ2vlA5Qmaoj65gKyD/ytr+BSXp3W,iv:4PSJtSnG2TtFHhPxXW1Y9ECEhnKXJmH01i7qnihSdSM=,tag:bzQyEbqYMOqnZe/oBZE6CA==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T10:50:16Z"
    mac: ENC[AES256_GCM,data:c8nhpcCpaiObl/cf4Ek8AHKSNqEXBnh4Jo9586PvKX1AbPWWiwSv2rhaoPzBrZLp5dG1MU4ysmdktb4Ar4xIdLWArZWPnewmuqkzsHZIzSoqHCFXdrXqSycJmpdn3gDdJ2NFrIqnRhwxl1uai4iRSmgwa2dCEaBSc/JU+96+dks=,iv:GltRPBQRltIZNe4vbH2YH+Pdq/L0FcZx19t8LHS3m0w=,tag:QYanDfJ0ivj1f/5h7aIKbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
