apiVersion: v1
kind: Secret
metadata:
    name: pangolin-proxy-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:IItEePHaPTbzMjzC/5Gt4IZB0n6J8bZFrrS3IyE=,iv:C+h/U1XMJugRUpX/MICHT6lXo7i3CGRK8BE5ytfw/1o=,tag:ILuBgvvVN5YFRJVotxOqKA==,type:str]
    OLM_ID: ENC[AES256_GCM,data:WMCnYCtmq/pN6s8tkjhL,iv:Wjlpe1bPzOgEb1BJ4Z24dX0VZVheI8MT4TMfYZWutEU=,tag:Xywxt9Xh6R0f7ilHXpBC9A==,type:str]
    OLM_SECRET: ENC[AES256_GCM,data:wEi2KnvaHFS59boE6a47UFHvA54xAevgYhjuQaM66/KTSIDBxktFtYTMIHLydEtX,iv:/IW7SXO6SaEfB2LmU0INvy3ISVD8gaHAs01bk+NV3DQ=,tag:SnKTHXWLRQKNVLgmXSVpeg==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T08:29:38Z"
    mac: ENC[AES256_GCM,data:k0Z4gqveX38dLQn6i9wjkH6/xy68ub4LHsKkvscblmR+2PM6KlRdpUsSF9eIW3jNqDEZpFyPgG+X5s6Kmzq2P1q49bSDz5IMz6GSsIPUsGaPsO9ogGoGM52rTxsXZ6Sk2dlZ9RKoSrIcZ5jMijDBCJxskbS+5oUuuGDj7JA++AM=,iv:uoUY9SU+1F0vof+zhKfLhscmQuqQyqeNDZc96mVVPIw=,tag:mGb+F+0dfKWwCAGklmCUVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
