apiVersion: v1
kind: Secret
metadata:
    name: pangolin-proxy-auth
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:IItEePHaPTbzMjzC/5Gt4IZB0n6J8bZFrrS3IyE=,iv:C+h/U1XMJugRUpX/MICHT6lXo7i3CGRK8BE5ytfw/1o=,tag:ILuBgvvVN5YFRJVotxOqKA==,type:str]
    OLM_ID: ENC[AES256_GCM,data:Tazel1BodLwvaUfsZFTw,iv:B51T/J7yn+Y3lzKrU2bIOO6oJpuXSpR80DHS3P2qtww=,tag:fZJBZWYXaoGbxsoehRGHmQ==,type:str]
    OLM_SECRET: ENC[AES256_GCM,data:69iR5Woh+NFePQ42N+R6T8Q3WShRbUpQulXBijDTKkDcRDqez/XKBA5E+DrbLXaY,iv:tVDY30Tmh7W57j0lLEyux4DsDtbekLWPI+GcG+W55Js=,tag:Buv1I9b2RqvwhC+9prQV5A==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T06:47:51Z"
    mac: ENC[AES256_GCM,data:uq2iaOZlJ0F+Nv/kAUB5b+XvgX9TZO5xpg73i1ovNX+5dntTzqWCHDKDcVYPYLbt2jTGngNe9EA0T4GTmJjyZClqN881hpE0I7lKqdKiuSJRxjd2Htdpit+e+u3o/RHisXeUGL96VW2VrQHCDX6Nc1IC5nOovAB1GmWDFtqtjzY=,iv:OaZmQ7PnqsKtvHOx0pQ4sr8N9phApM4bGp2wafrhY9I=,tag:OAxaGjKfuQfjllQDnoKXdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
