apiVersion: apps/v1
kind: Deployment
metadata:
  name: track
  labels:
    app: track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: track
  template:
    metadata:
      labels:
        app: track
    spec:
      containers:
        - name: track
          image: harbor.cloud.traunseenet.com/public/track:1.0.3
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: track-pg-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: track-pg-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: track-pg-app
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: track-pg-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: track-pg-app
                  key: password
          envFrom:
            - configMapRef:
                name: track-config
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
