apiVersion: v1
kind: Secret
metadata:
    name: s3-track-pg-backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1xwxPGTBcsurKQdtTHItP1TUbuA=,iv:V5yuGK1F70mufSJimbdBJyNT4azLkqx7NjluA3z+6H4=,tag:efWhxGKTbezX4KomkahNkA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OwxfjSnjuaoOsBFv4a2uXqTYfl+kVOueJWYz62poSRYUI5cDN6Zwrg==,iv:vg6iqrwBOC1dPcKZsFenABzkduxKcYDrrCxfiUTyQQQ=,tag:tlZYFFBHhrTWUz37Q0eoow==,type:str]
sops:
    age:
        - recipient: age1q3mu6g0l3kr7spszks69yqrvlxvlgfrqgw9r00qqt8cj9xpjd9mqdkd7um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcW84cS9aUlVEQUdDQWcy
            VDZhYnVEQ0tnSk5rSm1lVGRzNVlFVWdLU2tBCm05dXdZY1V5aWRMUnhLM1lhdWt2
            aG05NXRZOW9ncVlzTWQ3WnNvSFphZ0UKLS0tIGl0Qit2dEtxNlJ4c2xIbXp6ZzJ3
            cWFjZXdOVFR4ZTk3clMyYloxRFFwdEEKjUrIY/ognzS0Ed7l3I4Gc6lLn/ka6Cl2
            tf17o1WzwWJaz4goEftEXCt08YkTESs60hZghHwv09cYtp8K/+vwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T14:21:49Z"
    mac: ENC[AES256_GCM,data:RjhP1pohxunRfWQ+W+ulMosTIpeR0rQ1d0VQSRgVI3PMhSQwZjUM3gWHrCwg0FUzVAi0cHL2D6KS+p4qeyApB9a8kxnyzhNLkAU0VIeVTrqEgT2XSngIVN5ZvyZLz3IhmdK1gpCQEopXSd488wJcEvisSdirEps4uVN52Y9Wt9w=,iv:0qJt3Z9ulB/bXgsV5Fv9Kxi6RYIofbwfGVY7D0JWh0E=,tag:HwvE7W9fwBzg0Pv5lZEzJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
