---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
    defaultClass: false
    longhornUI:
      replicas: 1
    defaultSettings:
      backupTarget: "s3://flux-backup@us-east-1/"
      backupTargetCredentialSecret: s3-secret
      backupstorePollInterval: 30